### ISSUE TITLE
Use multiple classes in ui-sref-active

### ISSUE THREAD

**Issue by bampakoa** [angular-ui/ui-router#2481] opened 2016-01-25 15:54 UTC
Hi,

When I use multiple classes in an **ui-sref-active** directive I get the following error in console:

    [$parse:syntax] Syntax Error: Token 'class2' is an unexpected token at column 8 of the expression [class1 class2] starting at [class2].

AngularJS version: 1.3.20
UI-Router version: 0.2.16
Provided plunker: http://plnkr.co/edit/4y0KC38Vlnc57wy6owW9

**Comment by ahsile** [comment] 2016-01-25 16:18
+1 This bug is kicking my ass right now.

I checked the documentation and this still looks like it should work:

http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active

**Comment by nateabele** [comment] 2016-01-25 16:55
Wow, this looks like a legit regression. Sorry about that. Thanks for the report, I'll patch it up shortly.

**Comment by ahsile** [comment] 2016-01-25 17:01
I've been working on a simple fix. A try/catch around the $scope.$eval will work. Was just about to write a test and submit a PR.

[working code](https://github.com/ahsile/ui-router/commit/0f0a806e156eb2cfbfabac4790db7901e7641a7a)

**Comment by nateabele** [comment] 2016-01-25 17:03
Hah, that's basically what I just did. If you beat me to it, great. :smile:

**Comment by ahsile** [comment] 2016-01-25 17:14
PR Submitted. Feel free to do with it as you wish :smile:

**Comment by nateabele** [comment] 2016-01-25 17:23
Merged. I'll push a release shortly.

**Closed** 2016-01-25 17:22 UTC

**Comment by nateabele** [comment] 2016-01-25 17:32
Done: https://github.com/angular-ui/ui-router/releases/tag/0.2.17

**Comment by ahsile** [comment] 2016-01-25 17:50
Amazing. Thanks for the quick turnaround.

**Comment by nateabele** [comment] 2016-01-25 20:22
Happy to help. :smile:

**Comment by fpipita** [comment] 2016-02-17 08:16
@kmcarpenter could you please submit a PR for this one for `1.0.0alpha0` as well? It has the same issue, if you can't I'll do it. Thanks!
