### ISSUE TITLE
How to pass parameter with ui-sref between deeply nested objects?

### ISSUE THREAD

**Issue by maryampashmi** [angular-ui/ui-router#1951] opened 2015-05-12 11:11 UTC
Hi,

I got problem with how i pass parameter with ui-sref. This is post i have already put it in stackoverflow.

Hope any of you, can help me. 

http://stackoverflow.com/questions/30186531/how-to-pass-parameter-with-ui-sref-between-deeply-nested-objects

Thank you.

**Comment by eddiemonge** [comment] 2015-05-12 18:25
closing as duplicate of #1952

**Closed by eddiemonge** 2015-05-12 18:25 UTC
