### ISSUE TITLE
Uglify version 1.0.17

### ISSUE THREAD

**Issue by Bildelsbasen** [angular-ui/ui-router#3693] opened 2018-05-14 07:56 UTC
Im having trouble using uglify on version 1.0.17.
Getting following error:
`JS_Parse_Error {
  message: 'Unexpected token: punc ())'`

`stack: 'Error\n    at new JS_Parse_Error (/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)`

Best regards
Andreas

**Comment by mistic100** [comment] 2018-05-14 08:42
Somehow the problems seems to be with the TS compiler of ui-router/core

This line https://github.com/ui-router/core/blob/master/src/common/common.ts#L512 is compiled to 
```js
         result.push(
            args.map(function(array) {
              return array[i];
            }),
          );
```

**Comment by ohadcn** [comment] 2018-05-14 11:49
this breaks my entire build
I've locked my system to 1.0.15 for now

**Comment by bobbyziom** [comment] 2018-05-14 12:59
@mistic100 exactly the same for me with.

To run this version i needed to exclude it from grunt-contrib-concat, and extend the import manually afterwards.

Need to lock my dependencies!

**Comment by westy92** [comment] 2018-05-14 19:44
@mistic100 great find! Could this potentially be a TypeScript bug? According to the tsconfig.json, the project is targeting ES5: https://github.com/ui-router/core/blob/master/tsconfig.json#L7.

According to MDN, "**ECMAScript 2017** allows trailing commas in function parameter lists."
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_functions

**Comment by westy92** [comment] 2018-05-14 19:51
I copied the `export function arrayTuples(...args: any[]): any[] {` function to its own file and also copied the `tsconfig.json`. The resulting js did not have the trailing comma:

```js
            default:
                result.push(args.map(function (array) { return array[i]; }));
                break;
```

Something else must be adding it?

**Comment by mistic100** [comment] 2018-05-16 07:50
It was probably fixed by
https://github.com/ui-router/core/commit/578dc091914faac9954f9aed4765007b5c1acf76
and https://github.com/angular-ui/ui-router/commit/5fb93d042d5833514357d6e7956a4cf85be26900

now we need a release :-)

**Comment by r3plica** [comment] 2018-05-17 09:42
Can confirm that I am getting this too. Took me ages to find out the cause.....

**Comment by christopherthielen** [comment] 2018-05-19 18:25
This was a puzzler because the published code on NPM doesn't have any trailing commas.  Then I remembered that I added a git precommit hook which runs prettier on all staged files for commit.  Finally I remembered that bower publish commits bundled files to git. 

This issue only affects bower users.  (please stop using bower 😉)

I will fix this issue and publish a new release ASAP.

**Closed** 2018-05-19 18:31 UTC
