### ISSUE TITLE
Tests not compiling with 1.0.17

### ISSUE THREAD

**Issue by jgraham0325** [angular-ui/ui-router#3694] opened 2018-05-14 09:15 UTC
This is a (check one box):

- [x] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: 1.0.17

# Bug Report

#### Current Behavior:
On local machine:
1. bower update
2. gulp test

Getting an error running tests:
08:02:50 [INFO] [08:02:50] Starting 'test'...
08:03:23 [INFO] 14 05 2018 08:03:23.750:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
08:03:23 [INFO] 14 05 2018 08:03:23.758:INFO [launcher]: Starting browser PhantomJS
08:03:24 [INFO] 14 05 2018 08:03:24.159:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket P9liDdWm-S-ldcg9AAAA with id 54753505
08:03:24 [INFO] PhantomJS 2.1.1 (Linux 0.0.0) ERROR
08:03:24 [INFO]   SyntaxError: Unexpected token ')'
08:03:24 [INFO]   at /opt/jenkins/jenkins_slave/workspace/ui.app_00_verify/bower_components/angular-ui-router/release/angular-ui-router.js:989

#### Expected Behavior:

Tests pass, as they did a few days ago with 1.0.15

**Comment by davidwickman** [comment] 2018-05-16 19:55
looks to be a duplicate of https://github.com/angular-ui/ui-router/issues/3696 fixed in https://github.com/angular-ui/ui-router/commit/a1266b97328fe2aeb376fec87094fb8512b401bb#diff-ff25e0d5bd5e29e4c0a514d47835cc16

**Comment by christopherthielen** [comment] 2018-05-19 18:38
Should be fixed in 1.0.18
See https://github.com/angular-ui/ui-router/issues/3693

**Closed by christopherthielen** 2018-05-19 18:38 UTC
