### ISSUE TITLE
Alpha.4 has many TS7006 error "implicitly has an any type"

### ISSUE THREAD

**Issue by armorik83** [angular-ui/ui-router#2693] opened 2016-04-14 03:31 UTC
Hi.

In alpha.4 & TS 1.8.9 `"moduleResolution": "node", "noImplicitAny": true`

```
node_modules/angular-ui-router/commonjs/common/common.d.ts(13,37): error TS7006: Parameter 'X' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/common.d.ts(163,63): error TS7006: Parameter 'T' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/common.d.ts(163,66): error TS7006: Parameter 'key' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/common.d.ts(165,71): error TS7006: Parameter 'T' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/common.d.ts(165,74): error TS7006: Parameter 'key' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/hof.d.ts(113,27): error TS7006: Parameter 'ctor' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/hof.d.ts(113,37): error TS7006: Parameter 'x' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/hof.d.ts(115,27): error TS7006: Parameter 'comp' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/common/hof.d.ts(115,37): error TS7006: Parameter 'x' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/ng1/viewDirective.d.ts(10,9): error TS7010: 'resolve', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/angular-ui-router/commonjs/state/stateBuilder.d.ts(3,54): error TS7006: Parameter 'parent' implicitly has an 'any' type.
node_modules/angular-ui-router/commonjs/transition/transitionService.d.ts(75,35): error TS7006: Parameter 'error' implicitly has an 'any' type.
```

I encountered many TS7006 errors. please describes `any` correctly. thanks.

**Comment by majo44** [comment] 2016-04-14 13:45
+1

**Comment by christopherthielen** [comment] 2016-05-12 20:17
@armorik83 @majo44

Which package are you both referring to... the ng1 package?

We now publish `angular-ui-router`, `ui-router-ng2` and `ui-router-core` to **npm**.  You should use `npm install --save angular-ui-router@next`.  The package's `main:` points to the `release/angular-ui-router.js` bundle, and `typings:` points to the typescript definitions.

Then use `import {Thing} from "angular-ui-router";`  Your Typescript compatible IDE should find the typings automatically.

<img width="674" alt="screen shot 2016-05-12 at 3 17 04 pm" src="https://cloud.githubusercontent.com/assets/2053478/15229039/afad3cbc-1854-11e6-8f84-e729726af09f.png">

**Comment by christopherthielen** [comment] 2016-06-24 19:26
Closing as `wontfix` because typescript 2.0 has an option to skip lib checks 

https://github.com/Microsoft/TypeScript/pull/8735

**Comment by johnnyreilly** [comment] 2016-06-26 06:27
Unfortunately that means that users of the latest router will have to be on TypeScript 2.0 and have that option set given that using `noImplicitAny` is pretty commonplace.  That's a real shame.  I realise (having taken a look at it) that adding the necessary type annotations to resolve this issue isn't the work of 5 minutes but it's a shame to add extra requirements onto the users.  Would you be open to PRs to resolve this?  I may be able to slowly resolve this issue (though it might take a while as I don't know the codebase yet).

**Comment by johnnyreilly** [comment] 2016-06-28 12:00
So I got bold @christopherthielen - I've made a PR that makes ui-router `noImplicitAny` compliant.  I hope this works for you?

**Comment by johnnyreilly** [comment] 2016-08-02 05:13
Awesome!

**Comment by dballesteros7** [comment] 2016-08-17 14:50
Thanks @johnnyreilly. 

@christopherthielen  Btw, this not only produced error in the declaration files from ui-router but also in your own code if you do for example:

`
import {StateParams} from 'angular-ui-router'; 
class MyController($stateParams:StateParams) {
  let x = $stateParams['param'];
}
`
This throws on $stateParams being an implicity any even with --skipLibCheck, with this fix the problem is gone. Is there a nightly build one can use? or could we have a release with this fix in. Thanks!

**Comment by clembou** [comment] 2017-01-12 11:33
FYI I think `noImplicitAny` compatibility is broken again in `1.0.0-rc.1`:

```
ERROR in E:\repos\resgroup\smart-ui\node_modules\ui-router-core\lib\resolve\resolveContext.d.ts
(7,22): error TS7005: Variable 'NATIVE_INJECTOR_TOKEN' implicitly has an 'any' type.

ERROR in E:\repos\resgroup\smart-ui\node_modules\ui-router-core\lib\transition\transitionHook.d.ts
(13,37): error TS7006: Parameter 'error' implicitly has an 'any' type.

ERROR in E:\repos\resgroup\smart-ui\node_modules\ui-router-core\lib\common\common.d.ts
(361,31): error TS7006: Parameter 'a' implicitly has an 'any' type.

ERROR in E:\repos\resgroup\smart-ui\node_modules\ui-router-core\lib\common\common.d.ts
(361,34): error TS7006: Parameter 'b' implicitly has an 'any' type.
```

using [`--noLibChecks`](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new---skiplibcheck) as a workaround works as expected.

**Closed** 2017-03-12 17:56 UTC
Labels: 1.0, wontfix
