### ISSUE TITLE
Apply a custom animation to ui-view during resolve

### ISSUE THREAD

**Issue by jonrimmer** [angular-ui/ui-router#456] opened 2013-09-23 12:06 UTC
It would be very useful if ui-view ran a custom "resolve" animation between the beginning and end of a state change that affects it. This could be used to display a spinner or other loading animation, which is vital when the resolve includes fetching things from the server.

**Comment by viktordavidovich** [comment] 2015-01-03 04:42
thank's! last example looks like good.

**Comment by aikoven** [comment] 2015-01-20 11:00
My [SO answer](http://stackoverflow.com/a/28043609/829064):

My idea is to walk the path on state graph between transitioning states on `$stateChangeStart` and collect all involved views. Then every `ui-view` directive watches if corresponding view is involved in transition and adds `'ui-resolving'` class on it's element.

The [plunker](http://plnkr.co/edit/YZwGnHfIkSRxOlci8DHm) demo introduces two root states: `first` and `second`, the latter has two substates `second.sub1` and `second.sub2`. The state `second.sub2` also targets `footer` view that belongs to its grandparent.

**Comment by ClearCloud8** [comment] 2015-01-22 23:37
+1

**Comment by jumpwake** [comment] 2015-01-30 19:24
@aikoven +1

Kudos, this helped tremendously.  Tried everything I could find and nothing helped.  I used a slight variation of this, but it solved the processing lag issue.    The lag was not really evident until I bought an old Android phone to test with.  If I can get the UX to work well on this old device, it'll work great on anything.

**Comment by javoire** [comment] 2015-03-02 16:58
+1 

@antonpod your example worked great for simple ui view setups, as you said!

**Comment by PaddyMann** [comment] 2015-03-05 07:27
Bleugh - just walked into this unfortunate resolve limitation.

The behaviour I want is *similar* to @aikoven solution, but if I click on 'second.sub1' from 'first', I want the 'second' wrapper view to load immediately (as it only contains the section header), and the loader to only apply to 'second.sub1' (which happens to be a grid loading some data).

As it is, I'm ditching the use of resolves in favour of loading data on a service on onEnter, and watching the service to see if it is loading / loaded (- my service explicitly provides a 'loading' variable that can be watched).

**Comment by oravecz** [comment] 2015-03-05 15:20
@aikoven It seems like your solution is just a few steps away from using ng-enter/ng-leave semantics to enable ngAnimation capabilities.

**Comment by Maultasche** [comment] 2015-05-01 23:02
I solved the problem in my application by setting a flag in my controller when the state was changing and then hiding or showing a loading animation and my ui-view. If I was interested in which state was being transitioned from and to, that information is also available.

Code from the controller:
```Javascript
        //Flag that indicates if the state is changing
        vm.stateChanging = false;

        //Call some code when a state change starts
        $scope.$on("$stateChangeStart", function (event, toState, toParams, fromState, fromParams) {
            vm.stateChanging = true;
        });

        //Call some code when a state change finishes
        $scope.$on("$stateChangeSuccess", function (event, toState, toParams, fromState, fromParams) {
            vm.stateChanging = false;
        });
```

The web page:
```HTML
    <div ng-app="exampleApp" ng-controller="exampleController as example">
        <div ng-hide="example.stateChanging" style="margin-top: 10px;">
            <ui-view />
        </div>
        <div ng-show="example.stateChanging" style="margin-left: 10px;margin-top:10px;">
            <img src="/Content/Images/Shared/spinner-large.gif" alt="Loading..." />
            <span>Loading Page...</span>
        </div>
    </div>
```
The loading animation displays whenever I change states and it gets replaced by the view after the resolve has finished and the new state is ready.

**Comment by javoire** [comment] 2015-05-04 15:25
@Maultasche, I've done the same thing in some places, the problem is just that it doesn't solve the case @PaddyMann is describing

**Comment by doodirock** [comment] 2015-05-28 15:27
I know work was being done with this, but are we any closer to a solution for more complex routes?

**Comment by joshuahiggins** [comment] 2015-07-14 17:29
Is this something that is currently being implemented in a future version or would you welcome pull requests?

**Comment by gaui** [comment] 2015-07-24 11:38
:+1:

**Comment by nateabele** [comment] 2015-07-27 21:03
@joshuahiggins We haven't really come back to it yet. I think a PR might be a little premature, but if you want to take a look at our work on the [feature-1.0](https://github.com/angular-ui/ui-router/tree/feature-1.0) branch and propose a solution, we'd certainly be open to that.

At this point, the 1.0 code is still pretty experimental, so I'd hesitate to put a lot of time into a solution before validating that it conforms to the current design vision. Hope that makes sense. Thanks for the interest.

**Comment by eddiemonge** [comment] 2015-08-03 21:57
Closing this as it has a lot of stuff in it and a few workarounds. If someone wants to open a new issue for a feature request with a specific proposal, that would be greatly helpful. Like nate said, you can/should/please also try the new [feature-1.0 branch](https://gist.github.com/eddiemonge/f9f8cb0a9dc7f42515db) that is in development to see if its any better.

**Closed by eddiemonge** 2015-08-03 21:57 UTC

**Comment by gaui** [comment] 2015-10-14 00:45
How would I show an animation before state is loaded (promise resolve)?

**Comment by eddiemonge** [comment] 2015-10-14 02:37
you could attach it to the events: stateChangeStart and stateChangeSuccess

**Comment by gaui** [comment] 2015-10-14 02:46
Thank you @eddiemonge

**Comment by william-mcmillian** [comment] 2016-01-31 18:04
Here is a directive and service that allows simple control over showing loading states in the UI without abandoning pre-transition resolves


usage in html:

```
Home Page <a ui-sref="app.detail">Go to Detail</a>

<div loading-state="app.detail">Loading... (spinners, etc. can go here)</div>

```

implementation: 

```

myModule.directive('loadingState', function () {
    return {
        template: '<div ng-show="loading[state]" ng-transclude></div>',
        transclude: true,
        scope: {
            state: '@loadingState'
        },
        controller: function ($scope, loadingStates) {
            $scope.loading = loadingStates;
        }
    };
});

myModule.factory('loadingStates', function ($rootScope) {
    var loadingStates = {};

    $rootScope.$on('$stateChangeStart', function (event, toState) {
        loadingStates[toState.name] = true;
    });
    
    ['$stateChangeSuccess', '$stateChangeError', '$stateNotFound'].forEach(function (eventType) {
        $rootScope.$on(eventType, function (event, toState) {
            delete loadingStates[toState.name];
        });
    });

    return loadingStates;
});
```

**Comment by christopherthielen** [comment] 2016-01-31 18:45
nice @william-mcmillian

**Comment by jjenzz** [comment] 2016-06-02 16:59
I've created a directive that will emit `uiViewLoaderStart` or `uiViewLoaderStop` on the `$rootScope` when a `ui-view` is loading a new state. The events will get passed the `ui-view` element that is about to transition so you can do what you want with it (e.g. add/remove a class, append/remove content, hide/show your own custom loading directive).

```js
angular.module('uiViewLoader', ['ui.router'])
  .directive('uiViewLoader', () => {
    return {
      restrict: 'A',
      controller: UiViewLoader,
      controllerAs: '$ctrl'
    };
  });

class UiViewLoader {
  constructor($element, $rootScope, $attrs) {
    this._$element = $element;
    this._$rootScope = $rootScope;
    this._view = $attrs.uiView;
    this._state = $attrs.uiViewLoader.split('.').pop();
    this._regex = new RegExp(`^${this._view}`);
  }
  
  $onInit() {
    this._listeners = [
      '$stateChangeStart', 
      '$stateChangeSuccess',
      '$stateChangeError', 
      '$stateNotFound'
    ].map(event => {
      return this._$rootScope.$on(event, this._onStateChange.bind(this));
    });
    
    this._$rootScope.$emit('uiViewLoaderReady', this._$element);
  }
  
  $onDestroy() {
    // make sure destroy happens after 'uiViewLoaderStop' has fired
    const stopDestroy = this._$rootScope.$on('uiViewLoaderStop', () => {
      this._listeners.forEach(destroy => destroy());
      stopDestroy();
    }); 
  }
  
  _onStateChange(event, toState) {
    const segments = ['', ...toState.name.split('.')];
    const index = segments.indexOf(this._state);
    const isLoadingState = index > -1 && !segments[index + 2];
    const stateHasView = toState.views ? Object.keys(toState.views)
      .some(key => key.match(this._regex)) : !this._view;

    if (stateHasView && isLoadingState) {
      const isChangeStart = event.name === '$stateChangeStart';
      const emit = isChangeStart ? 'uiViewLoaderStart' : 'uiViewLoaderStop';
      this._$rootScope.$emit(emit, this._$element, toState);
    }
  }
}
```

To use it you need to add a `ui-view-loader` attribute to your `ui-view` element and pass it the name of the state that the `ui-view` lives on. For example:

```js
$stateProvider
  .state('root', {
    abstract: true,
    resolve: {
      data($timeout) {
        return $timeout(angular.noop, 1000);
      }
    }
  })
  .state('root.about', {
    url: '/about',
    resolve: {
      data($q, $timeout) {
        return $timeout(angular.noop, 1000);
      }
    },
    views: {
      'main@': {
        template: `
          <h2>About</h2> 
          <div ui-view ui-view-loader="root.about"></div>
        `
      }
    }
  });
```

If you do not pass a state name it will assume `$default` state.

I have created a codepen demonstrating how this can be used with your own custom `load-spinner` directive to show custom spinners when a particular `ui-view` is loading: http://codepen.io/jjenzz/pen/RRNXKQ?editors=1010

If anyone can think of ways to improve this, please do share... I'm no genius 😄
