### ISSUE TITLE
$state.go does not transition when notify: false is set

### ISSUE THREAD

**Issue by Bekt** [angular-ui/ui-router#2245] opened 2015-09-16 06:10 UTC
v: 0.2.15
Plunker: http://plnkr.co/edit/T1zeCJGKTLdYoDSHcj6u

**Summary:**

The current state (`parent.one`) fails to transition with the following code:
```js
$state.go('parent.two', {}, {notify: false});
```

It transitions fine with the default options:
```js
$state.go('parent.two');
```

**Expected Behavior:** 
The first snippet should behave exactly like the second snippet with only exception of even broadcasts.

On the Plunker example, if you click on "Child One" , the state should transition to `parent.two` within `parent.one`.

**Comment by eddiemonge** [comment] 2015-09-17 19:08
This is a duplicate of a known problem. `notify` wasn't the best implemented feature.

**Closed by eddiemonge** 2015-09-17 19:08 UTC

**Comment by Bekt** [comment] 2015-09-17 21:28
Which one? I've looked over all open issues thay I could find related to notify and this is different than all.
