### ISSUE TITLE
Params and $urlRouterProvider

### ISSUE THREAD

**Issue by lucasengel** [angular-ui/ui-router#2734] opened 2016-05-09 20:02 UTC
I'm trying to create several routes with the same pattern:
```
/create
/:id/view
/:id/edit
/:id/delete
```
and I'm using $urlRouterProvider to redirect anyone accessing `/:id` to `/:id/view`

Problem is: on some pages when trying to access `/create` the user will be redirected to `/create/view/`

Is this something known?

**Comment by eddiemonge** [comment] 2016-05-12 17:38
How are you redirecting? Can you do a plnkr? There isnt a whole to go on from this.

**Comment by lucasengel** [comment] 2016-05-12 19:17
I'm not being able to reproduce the problem on plnkr but here's a sample of the code:

```
$stateProvider
  .state('main', {
    url: '/',
    template: '<h1>Home</h1><ui-view></ui-view>'
  })
  .state('main.users', {
    url: '/users',
    template: '<h2>Users</h2><ui-view></ui-view>'
  })
  .state('main.users.create', {
    url: '/create',
    template: '<h3>Create</h3>'
  })
  .state('main.users.user', {
    abstract: true,
    url: '/:_id',
    template: '<ui-view></ui-view>'
  })
  .state('main.users.user.view', {
    url: '/view',
    template: '<h3>view</h3>'
  })

$urlRouterProvider
  .when('/users/:_id', '/users/:_id/view')
```

**Comment by eddiemonge** [comment] 2016-05-23 19:11
Can I close this since without a working broken example its hard to troubleshoot and reproduce the issue

**Comment by lucasengel** [comment] 2016-05-23 19:57
I've tried reproducing it in a separate file but I couldn't. So, yes, go ahead and close it, please

**Closed** 2016-05-23 21:43 UTC
Labels: PlunkrPlease
