### ISSUE TITLE
Strategies for migrating from server-side router?

### ISSUE THREAD

**Issue by andrewboni** [angular-ui/ui-router#2077] opened 2015-07-03 20:27 UTC
I have a large web app with >100 routes defined, all using the server-side router of my framework. I'd like to switch over to `ui-router`, but need to be able to switch over just a handful of routes at a time, instead of all of them in one fell swoop, to ensure a smooth transition/UX for my users.

Is there a good strategy/workaround for doing a router transition piece by piece? The main issue that I'm running into is when attempting to navigate from a server-side defined route to a client-side one (controlled by `ui-router`). This is because the rendered DOM from the server is still present. Things like `ng-show` and `ng-if` may help here, but they seem like hacks at best.

The opposite scenario (going from a client-side defined route to server-side defined route) works fine however, as a full page refresh occurs.

Would love to hear any thoughts/strategies from those who've done something similar. Thanks!

**Comment by eddiemonge** [comment] 2015-07-07 19:55
This is a great question for stackoverflow.

Closing since its not a bug and you will get better help for this on SO

**Closed by eddiemonge** 2015-07-07 19:55 UTC
Labels: StackOverflow
