### ISSUE TITLE
additional Hashtag in URL won't match state? (in html5mode)

### ISSUE THREAD

**Issue by gdipkf1986** [angular-ui/ui-router#2209] opened 2015-08-26 08:49 UTC
```javascript
$locationProvider.html5Mode(true);
$stateProvide
.state('roo',{url:'', template:'<ui-view />'})
.state('root.action', {url:'/:module/:action'})
```

when jumping from **/m1/a1#** to **/m1/a2**, state will change and auto load resources by resolve obj, but if using browser back button from **/m1/a2** back to **/m1/a1#** then nothing happen, then state won't change. 
If change **/m1/a1#** to **/m1/a1**(removed ending hashtag) then then back button works.

**Comment by eddiemonge** [comment] 2015-08-26 18:58
calling this a duplicate of https://github.com/angular-ui/ui-router/issues/2115 even though it might not be. lets see if fixing that one fixes this one, if not we can reopen

**Closed by eddiemonge** 2015-08-26 18:58 UTC

**Comment by mssalnikov** [comment] 2016-08-24 22:44
@eddiemonge apparently it did not, I'm still having the same issue. Or at least one that looks similar: 
I have a state that should match `#?[0-9]+`, and it doesn't, when the hash sign is there
