### ISSUE TITLE
1.0 Why can't I go from query url to non-query url?

### ISSUE THREAD

**Issue by shawnlan** [angular-ui/ui-router#3019] opened 2016-09-19 20:08 UTC
Here is the plunker: http://plnkr.co/edit/A9JXGVO9qhFrB9LBtBOa?p=preview

Click the link "with query" and then click the link "without query." The url won't change back to without query.

Is it a bug or intended? Why?

**Comment by christopherthielen** [comment] 2016-09-19 20:34
It's because `ui-sref` (and `$state.go()`) inherits the current parameters by default.  Add `ui-sref-opts="{ inherit: false }"` or pass `undefined` for the parameter value

```
      <a ui-sref="home({test:1})">with query</a> <br>
      <a ui-sref="home" ui-sref-opts="{ inherit: false }">inherit: false</a> <br>
      <a ui-sref="home({ test: undefined })">test: undefined</a> <br>

```

http://plnkr.co/edit/JH8XB6r0YefE4JVbzl4Q?p=preview

**Comment by adharris** [comment] 2016-09-19 20:34
This is the intended behavior.

By default, unspecified values for params will be inherited from the current state.  This allows you to not worry about specifying all params when creating a link.  For example, imagine a state that contains a list of items that is searchable, sortable, and paged.  You could have state params for each of `search`, `sort`, and `page`.  This functionality allows you to do a next page link `<a ui-sref='stateName({page: page+1})>` without having to specify sort and search.  Your pager link doesnt have to know about the rest of the params.

This is not always what you want.  there are two ways to get the behavior your looking for:

* Specify `null` as the value for the parameter
* Use the `ui-sref-opts` attribute and specify `{inherit: false}`

The first will clear the value for a specify param, while the latter will disable param inheritance for the link.

plunk: http://plnkr.co/edit/fmY8VGT9gNFqwGMuoEkz?p=preview

**Closed** 2016-09-19 20:34 UTC

**Comment by shawnlan** [comment] 2016-09-19 22:15
Got it. However, if the url is in a form like "/test/:value", then it won't inherit anyway. Such inconsistency is kind of confusing?

**Comment by christopherthielen** [comment] 2016-09-19 22:20
it will inherit :value too.

http://plnkr.co/edit/SNaaGXbNFhXFtdJhq6SL?p=preview

**Comment by shawnlan** [comment] 2016-09-19 23:22
Sorry my bad. I confuse it with something else, but it's clear now. Thanks for your explanation.
