### ISSUE TITLE
$state.go() returns a resolved promise before transition to new template

### ISSUE THREAD

**Issue by checo06** [angular-ui/ui-router#3051] opened 2016-09-29 15:43 UTC
As the title says, im making a $state.go() and returns a resolved promise before transition to new template.. is this the normal behaviour of $state.go()?

Im mixing Q and $q promises so maybe it makes a problem altought im doing the $state.go() call inside $timeout() to guarantee it is executed under the angular digest cycle.

I want to wait until the new template is shown to execute a chaining code from the promise.

**Comment by christopherthielen** [comment] 2016-10-26 17:56
> is this the normal behaviour of $state.go()?

Yes.

State transitions (and their promises) resolve _before the views are updated_.  
To put it another way, the views are updated  _in response to a successful state transition_.

Because of things like `ng-if` (turning ui-views off based on logic), template fetching for components (async), etc, we can't deterministically wait until "all the views are a rendered" to resolve the transition promise.

We do have the `$viewContentLoaded` event to listen to, but I admit I don't think it's all that useful.  https://github.com/angular-ui/ui-router/blob/72b67cc48a0656731e9d8d9380e4972d3770ad45/src/ng1/directives/viewDirective.ts#L312-L323


What version of ui-router are you using?  In 1.0 you should be able to add a low priority `onSuccess` handler that is invoked **after** [the views are updated](https://github.com/ui-router/core/blob/8571ee281a16c16add841c6c57fcfedd1c788e36/src/hooks/views.ts#L28-L52).

```
var trans = $state.go('foo').transition;
trans.onSuccess({}, function() { /** do stuff */ }, { priority: -1 });
```

Closing because this is expected behavior.

**Closed by christopherthielen** 2016-10-26 17:56 UTC
