### ISSUE TITLE
Access URL containing hash directly with HTML5Mode on 

### ISSUE THREAD

**Issue by hugsbrugs** [angular-ui/ui-router#2134] opened 2015-07-27 21:48 UTC
Hi everybody !

Here is my headache of the day : Using ui-router 0.2.15, angular 1.3.17, HTML5Mode is activated, Apache .htaccess relevant part is : 
```
<ifModule mod_rewrite.c>
    RewriteEngine On

    # REDIRECT HTTP TO HTTPS
    RewriteCond %{SERVER_PORT} 80
    RewriteRule ^(.*)$ https://www.my-website.com/$1 [R,L]

    # REDIRECT ALL NON-WWW TO WWW
    RewriteCond %{HTTP_HOST} ^my-website.com
    RewriteRule (.*) https://www.my-website.com/$1 [R=301,L]

    # FOR ANGULAR -> redirect everything to index.html except directories api & assets & admin
    RewriteRule ^(api|assets|admin)($|/) - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !index
    RewriteRule (.*) index.html [L]
</ifModule>
```

I can navigate between different states using : 
```javascript
$state.go(my_state, {'#':my_hash});
```
hash is correctly appended to url and with this HTML : 
```html
<div ui-view autoscroll="true"></div>
```
and javascript config block : 
```javascript
$uiViewScrollProvider.useAnchorScroll();
```
run block
```javascript
$anchorScroll.yOffset = 80;/* because of a fixed bootstrap navbar, I need an offset */
```

the router automatically scrolls to my element with id="my_hash"

So everything would be perfect IF I could access my states when doing a page refresh or a direct access to an URL like : 
https://www.my_website.com/my_state_url_path#my_hash

when I do so, everything which is after # is removed from the URL. I'm pretty sure it doesn't come from .htaccess. 

Is there any declaration to do in state definition to make it works ? Does it works out of the box for you ? Thanks for any suggestions !

Hugo 

**EDIT**
It is now sure it comes from my router's config because doing a simple :
https://www.my_website.com#hello
keeps the "hello" so I have to precise I'm using nested states and now believe hash is lost between state transition ... and seems to be linked to https://github.com/angular-ui/ui-router/issues/510

**Comment by eddiemonge** [comment] 2015-07-28 17:51
Closing as a duplicate of #510 since it does seem to be the same.

**Closed by eddiemonge** 2015-07-28 17:51 UTC
