### ISSUE TITLE
Bootstrapping for phonegap/cordova

### ISSUE THREAD

**Issue by astutesoftware** [angular-ui/ui-router#2262] opened 2015-09-23 17:54 UTC
I have a page that uses angular ui-router to render two views on the same page. I ultimately need to have this run under phonegap/cordova so will have to bootstrap angular to the elements on a deviceready event.

I managed to encapsulate the code into a function and when the function is called at the end of the page it works fine.

However when the same function is called on the window.onload or document ready event it fails to work. In fact if the function is called from the javascript console itself after page load it just fails to work.

Need help figuring out what is exactly going wrong.

code here: http://geo.tikoo.com/bootstrap.php#/messaging

**Comment by wesleycho** [comment] 2015-09-24 04:34
I don't know of there being any particular problem with this when using Cordova from my experience - without an adequate reproduction, I'm not sure there is much we can do.

**Comment by wesleycho** [comment] 2015-09-24 04:35
In addition, that code is using an old version of Angular and UI Router. You should also load jQuery before Angular.

**Comment by astutesoftware** [comment] 2015-09-24 04:52
Thanks for the response.
I used the latest version of angular, router and jquery. Also moved jquery to load before angular as you suggested, the problem persists.
Leaving cordova aside - if we have a function that bootstraps and we want to call it at will that is where i am having an issue. I uploaded a version using the changes you mentioned here.
http://geo.tikoo.com/del_views.php#/messaging
i have the function call at the end of the page and it works perfect.

If i call the same function at will or at body load/window load (and eventually ill be calling it at device ready under cordova) it does not work at all. 

In fact if i dont call the function immediately i see this error in my console log
"Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.6/$injector/modulerr?p0=routerApp&p1=Error%…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.6%2Fangular.min.js%3A19%3A463)"

Im setting up two pages for your quick viewing
1. http://geo.tikoo.com/del_views.php#/messaging 
    this is perfectly working with my function called at the end

2. http://geo.tikoo.com/del_views_error.php#/messaging
    ditto copy of the 1st. except that i remarked the function being called at the end.
    this page throws the error i mentioned above.

**Comment by wesleycho** [comment] 2015-09-24 05:01
Other things I am noticing - you are using ng-app on a higher level element, and are bootstrapping apps on children elements. This is a big nono.

**Comment by wesleycho** [comment] 2015-09-24 05:03
So the second one is erroring because you need to execute `doit` in order for the `routerApp` module to even be defined.

**Comment by astutesoftware** [comment] 2015-09-24 05:32
1. Should i construct another div and use ng-app on it?
2. Yes doit function has to be called to define routerApp. The question is why a delay in calling the function throws the error. I need to call the doit function on device ready or some other initialization process. the second url throws an error and even if we call the doit function via the javascript console or through a button click event it fails to work.

Here is what i am trying to.
1. Have clean dom (just plain head,body tags) and wait for deviceready event.
2. On device ready populate my header files (js/css) via head.js one by one. (later in the future.)
3. Then go about adding the ng-app directive to an element in my dom. (this can be hardcoded)
4. Populate my view elements (this can be hardcoded).
5. lastly have the doit function that does my bootstrapping.

If there is another way to do this i would like to hear it.
Thanks again for your valuable time. Hope i have tried to explain my scenario clearly.

**Comment by wesleycho** [comment] 2015-09-24 05:35
If you are bootstrapping your app, there is no reason to use ng-app - this is likely the cause of your problem then, as ng-app will attempt to bootstrap your app on the load event, but if your module is not present, then it will throw an error.

Your best bet is to remove ng-app completely, and bootstrap your app just once (no for loop) to the html or body element.

**Comment by wesleycho** [comment] 2015-09-24 05:35
Closing issue as support

**Closed by wesleycho** 2015-09-24 05:35 UTC

**Comment by astutesoftware** [comment] 2015-09-24 06:22
figured it out.
angular.element(element).ready would be the event to wait for.
thanks a bunch
