### ISSUE TITLE
No values in $stateParams

### ISSUE THREAD

**Issue by worrel** [angular-ui/ui-router#136] opened 2013-05-21 18:19 UTC
I posted this on Google+ earlier. Here's a plunker demonstrating my problem: http://plnkr.co/edit/bKN08D7kaKCzy2PrStOK?p=preview

Basically, the **$stateParams object never appears to get populated with URL param values**.  I suspect I'm just missing something simple, but I can't figure out what.  Any help appreciated.

**Comment by dubcanada** [comment] 2015-02-09 21:07
I am also getting this error.

**Comment by shank8** [comment] 2015-02-26 23:17
I am getting the same problem that @Emanuele-Spatola stated where I can see the $stateParams in the resolve but not in the factory service that is doing the resolve right after that..

```
 .state('customer.users', {
            url:'/users',
            controller: 'CustomerUsersController',
            resolve: {
                UserList: function(Users, $stateParams){
                    return Users.query().$promise; //$stateParams.customerId IS defined here
                }
            }
        })
```

BUT

```
app.factory('Users', function(API, $stateParams){
    var service = {};
    var resource = null;

    service.query = function(callback){
        if(!resource){
            resource = API.MaaS.CustomerUser.query({customerId: $stateParams.customerId}, callback); // WHY IS $stateParams NOT DEFINED HERE!!!!!
        }else if(callback){
            callback(resource);
        }

        return resource;
    }

    return service;
});
```

**Comment by woutercleymans** [comment] 2015-03-05 15:28
I'm also getting the same error using the following config:

```javascript
$stateProvider
            .state('user', {
                url: '/user',
                controller: 'UserCtrl',
                templateUrl: 'templates/user.tpl.html'
            })
            .state('user.tab', {
                url: '/{tab}/{id:int}',
                params: {
                    tab: {
                        value: null,
                        squash: false
                    },
                    id: {
                        value: null,
                        squash: false
                    }
                }
            })
        ;

// $stateParams object is empty inside the controller!
```

**Comment by woutercleymans** [comment] 2015-03-05 16:56
It looks like it works when I move the "params" to the parent state.

**Comment by shivenigma** [comment] 2015-03-31 07:36
I am also having this issue. 

my app.js looks like this. 

(function(){
    "use strict";
    var app = angular.module("productManagement",
                            ["common.services","ui.router"]);
    app.config(["$stateProvider","$urlRouterProvider",function($stateProvider,$urlRouterProvider)
        {
            //default
            $urlRouterProvider.otherwise("/");

            $stateProvider
                //home
                .state("home",{
                    url:"/",
                    templateUrl:"app/welcome.html"
                })
                //products
                .state("productList",{
                    url:"/products",
                    templateUrl:"app/products/productListView.html",
                    controller:"ProductController as vm"
                })
                //Edit product
                .state('ProductEdit',{
                    url:"/products/edit/:productId",
                    templateUrl:"app/products/productEdit.html",
                    controller:"ProductEditController as vm"
                })
                //product details
                .state('ProductDetails',{
                    url:"/products/:productId",
                    templateUrl:"app/products/productDetailView.html",
                    Controller:"ProductDetailController as vm"
                })
        }]
    );
}());

I am trying to get the product Id from the Prodcut details route to my controller which is below. I can't get that. what I am doing wrong. I am a very beginner to angular. so can't figure out anything.

(function(){
    "use strict";
    angular
        .module("ProductManagement")
        .controller("ProductDetailController",
                    ["ProductResource",$stateParams,ProductDetailsController]);
        function ProductDetailsController(ProductResource,$stateParams)
        {
            alert('test');
            var productId = $stateParams.productId;
            var ref = $this;
            ProductResource.get({productId: productId},function(data)
            {
                console.log(data);
            });
        }
}());

**Comment by Morriz** [comment] 2015-04-13 07:30
Could someone please give us a response? Or is this project dead?

**Comment by shivenigma** [comment] 2015-04-13 10:04
@Morriz I overcame this by using a resolve, though this may be an overkill I just needed to do that.
Just pass your $stateParams inside your resolve function then return the required parameters from their. You can then get it inside the controller. Hope it helps

**Comment by Morriz** [comment] 2015-04-13 11:11
The params are not yet populated in the resolve phase for child states (bug imo, not a feature), so that is not an option...

**Comment by jtyagi** [comment] 2015-07-31 07:18
You could try with $state.params.variableName. I was facing the same problem and it is resolved now. but i could not figure out why params was not reflected in $stateParams.

**Comment by uggel** [comment] 2015-07-31 08:57
So, global stateParams do not get populated in states that do not use those params in their controller... right?
Now, I have an abstract state declaring the controller for all childstates (unless specified on the childstate). I would consider that controller global for all the states, thus used by all childstates...

Ok, it does not work this way, i use $state.params instead. But... is this a bug/mistake or could someone direct me to a document explaining the beauty that I missed out.

**Comment by Morriz** [comment] 2015-07-31 11:33
I figured it out I think, and it seems to work like this:

$stateParams are only to be used in resolve functions in the router, where they have their proper values, but $state.params is still empty (preflight state).

$state.params is populated before injection into the controllers, and should only be used there.

So be careful with injecting any of the two into anything other than a controller. You then need a mechanism to ensure they are populated.
But this last bit might already be fixed. Maybe $state.params is populated before being injected into anything now. Does anybody know this, or wants to check?

**Comment by uggel** [comment] 2015-07-31 11:53
@Morriz That's exactly what I just discovered :)
I believe Angular gets a bit hacky under the hood sometimes... this is one of those. 
$stateParams, $state.params... why have 2? Probably because of the architecture.

**Comment by wesleycho** [comment] 2015-07-31 13:50
@Morriz: that is correct - `$stateParams` is a special object that gets filled during the resolve for each state with only that state's parameters, and $state.params only gets filled with every state's parameters once the state transition is complete.

Not sure if the docs are clear on this, but if not, we should update the wiki to emphasize this.

**Comment by Morriz** [comment] 2015-07-31 14:22
:)

**Comment by mryarbles** [comment] 2015-08-04 20:06
Ok this is driving me nuts....

I have a root controller attached to body using ng-controller using the following code.

```javascript
var Controller = function ($rootScope, $scope, $state, $http, $timeout, $log, $stateParams) {

            $log.log("AppCtrl");
            $log.log($state);
            $log.log($state.params);

}

Controller.$inject = ['$rootScope', '$scope', '$state', '$http', '$timeout', '$log', '$stateParams'];
```

The second log shows me this (notice that params is full of values): 

![image](https://cloud.githubusercontent.com/assets/1441751/9071244/bb168546-3aa0-11e5-84ca-2a3f8d097f0d.png)

The third log traces an empty object, and the fourht is undefined
![image](https://cloud.githubusercontent.com/assets/1441751/9071317/29e0a416-3aa1-11e5-92ac-5ac1c9aee636.png)

I am at a complete loss as to why I can't access the values of $state.params....

**Comment by uggel** [comment] 2015-08-04 20:13
@mryarbles  Just for the fun of it... try logging $stateParams as well.

**Comment by mryarbles** [comment] 2015-08-04 21:08
@uggel I tried that, but it's an empty object. It should be empty though because this is "Root" controller that is not directly associated with a router state. 

What I wound up doing was accessing the values after the $stateChangeSuccess event

```javascript
            $rootScope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState, fromParams) {
                $log.log("AppCtrl.onStateChangeSuccess");
                $scope.containerClass = toParams.platform;
            }); 
```

I just for the life of me can't understand why I can't access params values when they are clearly there!

**Comment by ka8725** [comment] 2015-08-25 16:12
Had the same issue. This is my defined states:

```
app = angular.module('App', ['ui-router'])
app.config(
  function($stateProvider, $urlMatcherFactoryProvider) {
    $stateProvider.
      state('menu', {
        url: '/menu',
        controller: 'ParentCtrl',
        templateUrl: '/menu.html'
      }).
      state('menu.item', {
        url: '/:menuItem',
        controller: 'ParentCtrl',
        templateUrl: '/menu.html'        
      })
  }
);
```

And in the `ParentCtrl` injects `$stateParams`, but `$stateParams` is empty. Interestingly that to fix that problem you don't have to change this code at all. The problem, probably, in your templates. Note that the both states use the same template - `/menu.html` and the problem is that the template doesn't have `<ui-view>` inclusion.

So in my case I just added `<ui-view>` in the bottom of the template and it started to work correctly:

Was:
```html
<some-html-code></some-html-code>
```

Now:
```html
<some-html-code></some-html-code>
<ui-view></ui-view>
```

This weird behaviour explained by that fact that ui-router resolves `$stateParams` for controllers only for views. So if your parent state's view doesn't have `ui-view` call then children states' resolved won't be waited before initializing it's controller. This is clear from these [lines of code](https://github.com/angular-ui/ui-router/blob/master/src/state.js#L1380-L1435).

**Comment by morfin** [comment] 2015-10-12 20:48
@cxyokk How did you solve the problem with child views ?

**Comment by changsongbu** [comment] 2016-08-11 21:53
I had the same issue and spent the whole day trying to figure out the reason. Turns out to be my url syntax on the browser. I was testing on my local server.

So the following formats work:
http://localhost:9000/#/id=cloudy
http://localhost:9000/#/simba

Following don’t work: 
http://localhost:9000/cloudy
http://localhost:9000/id=cloudy
http://localhost:9000?id=cloudy
http://localhost:9000/?id=cloudy
http://localhost:9000/#/?id=cloudy

I don't know why # is important but if left out, none of the url will work.

State is defined as following
// Routes
myModule.config(['$stateProvider', function($stateProvider) {
    $stateProvider
        .state('myRecords', {
            url: '/:id',
            controller: 'myCtrl',
            templateUrl: 'modules/views/myRecords.html',
        });
}]);

**Comment by sadlerw** [comment] 2016-08-14 15:21
So, admittedly not best, but I was able to get all of the values needed by the child states to resolve in the abstract parent state by simply starting with a resolve that used $location.path().split('/')[2] to get the part of the path represented by the stateParam as :param in the child definition.  The resolves in the abstract parent then can include that, e.g.

    resolve:
        urlPathSegment: [
          '$location'
          ($location) ->
            $location.path().split('/')[2]
        ]
        anotherValue: [
          'urlPathSegment'
          'someService'
          (urlPathSegment, someService) -> someService.getSomething(urlPathSegment)
        ]

**Comment by worrel** [comment] 2016-08-14 16:47
3+ years since I filed it this issue still brings my inbox such joy :-P

**Comment by wesleycho** [comment] 2016-08-14 16:57
Given that the relevant information is now in the [wiki](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#issue-what-is-the-difference-between-stateparams-and-stateparams), I'm closing this as resolved.

This thread also contains a wealth of information that users can use to figure out why their `$stateParams` is empty. Just to recap - `$stateParams` when injected in controllers are locals, not the global `$stateParams` service. The local version only contains the state params for that specific state, whereas `$state.params` contains the global params for the current active state.

**Closed by wesleycho** 2016-08-14 16:57 UTC
Labels: pull-to-faq

**Comment by UncleGoogle** [comment] 2018-06-07 17:50
Similar issue as vintots

code below using ui-router.stateHelper
```javascript
{
    name: 'packages',
    url: '/packages',
    templateUrl: 'packages.html',
    children: [
        {
            name: 'files',
            url: '/files',
            params: {
                packageId: null
            },
            onEnter: ['$stateParams', '$state', '$uibModal', '$timeout', function($stateParams, $state, $uibModal, $timeout) {
                console.log($state.current.name)  // -> packages
                console.log($stateParams.packageId) // -> ok
                $timeout(function() {
                    $uibModal.open({
                        templateUrl: 'fdContent.html',
                        controller: ['$state', function($state) {
                            console.log($state.current.name)  // -> 'packages.files'   |  without $timeout -> 'packages'
                            console.log($stateParams.packageId) // -> ok   |   without $timeout -> undefined
                        }]
                    }).result.finally(function () {
                        $state.go('^');
                    })
                });
            }],
        }
    ]
},
```
