### ISSUE TITLE
ui-sref doesn't work with null since v. 0.2.14

### ISSUE THREAD

**Issue by tamtakoe** [angular-ui/ui-router#1958] opened 2015-05-14 09:49 UTC
`ui-sref="contacts.detail({ param: null })"`

**Comment by moarsel** [comment] 2015-05-14 13:59
state.go with params also stopped working in 0.2.14:

$state.go('history', { pendingActive: false});

There's no error, but the page does not change.

**Comment by eddiemonge** [comment] 2015-05-14 18:00
duplicate of #1915

**Closed by eddiemonge** 2015-05-14 18:00 UTC
