### ISSUE TITLE
Encode/decoding params behaviour

### ISSUE THREAD

**Issue by huyph** [angular-ui/ui-router#2376] opened 2015-11-18 05:22 UTC
Here is an example:
I have this state, which takes in a query and show some search results for that query
```javascript
  .state('app.result', {
    url: '/result-page/:query',
    templateUrl: 'componenets/app/result.html',
  });
...
...
somewhere I redirect user to this page
...
$state.go('app.result', {
  query: 'king/'
});
```

The URL is encoded so if submit a query 'king/'. The URL will then be translated to 'http://..../result-page/king%252F', which is understandable.

But then, if I refresh the page or send this URL to someone else. They will be viewing results for 'king%252F' not 'king/'. It is because ui router does not decode it. 

I know i can create a custom type using `$urlMatcherFactoryProvider`.

But this seems like a common problem. Why don't we decode it by default? Am i missing something?

**Comment by huyph** [comment] 2015-11-18 06:04
Further investigations suggest me that that behaviour is coming from these codes:
```javascript
    string: {
      encode: valToString,
      decode: valFromString,
      is: function(val) {
        return typeof val === "string";
      },
      pattern: /[^/]*/
    },
```

```javascript
/** Given an encoded string, or a decoded object, returns a decoded object */
Type.prototype.$normalize = function(val) {
  return this.is(val) ? val : this.decode(val);
};
```

I think $normalize is called when reading parameters from the URL. If I don't specify a type for a parameter, then it will be of type String by default. And for String type declaration above, it won't be decoded because it is of type string (?)

**Comment by eddiemonge** [comment] 2015-12-03 01:01
Duplicate of #1645

**Closed by eddiemonge** 2015-12-03 01:01 UTC
