### ISSUE TITLE
UI Router 1.0.0 delete query parameters on reload

### ISSUE THREAD

**Issue by inkstak** [angular-ui/ui-router#2730] opened 2016-05-07 12:31 UTC
Hi,  
Since 1.0.0, when I'm going to a state, adding an optional query parameter and reloading the page, the query parameter disappears.

Here is an example, running with ui-router 0.2.18.
- go to #/?foo=bar
- the url is still #/?foo=bar
- the console output returns :
  - `window.location.hash` equals `#/?foo=bar`
  - `$location.url()` equals `/?foo=bar`

When switching to v1.0.0-alpha.4 :
- go to #/?foo=bar
- the url becomes #/
- the console output returns :
  - `window.location.hash` equals `#/?foo=bar`
  - `$location.url()` equals `/`

```
<!DOCTYPE html>
<html lang='fr' ng-app='app'>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.18/angular-ui-router.js"></script>
    <script>
      angular
        .module('app', ['ui.router'])
        .config(['$urlRouterProvider', '$stateProvider',
          function ($urlRouterProvider, $stateProvider) {
            $urlRouterProvider.otherwise("/");
            $stateProvider.state('search', {
              url:          "/",
              templateUrl:  "/template.html",
              controller: ['$location', function ($location) {
                console.log(window.location.hash, $location.url())
              }]
            })
          }
        ])
    </script>
  </head>
  <body>
    <div ui-view></div>
    <script id='/template.html' type='text/ng-template'>
      <div></div>
    </script>
  </body>
</html>
```

**Comment by christopherthielen** [comment] 2016-05-07 17:04
Verified, this is a regression. Thanks for the bug report

**Comment by christopherthielen** [comment] 2016-05-07 17:16
It looks like the fix for #1573 never merged into the 1.0 codebase.

The fix will be to set `location: false` for transitions that originate from a URL parse.  `location: false` tells the transition NOT to update the location after the transition succeeds.

In the plunker, click "add query param" then click "reload". The URL *should not* change because the transition originated from a url parse.

Subsequent normal navigations (ui-sref, etc) will clobber the url, clearing the query string (this is how 0.2.18 works also). In the plunker, click "add query param" button, then the `search2` ui-sref; query string is cleared.

http://plnkr.co/edit/j7xRtpcMEkTqhREMiCkt?p=preview

**Comment by inkstak** [comment] 2016-05-07 17:43
Thanks. Waiting for alpha 5.

**Closed** 2016-05-12 21:34 UTC
Labels: 1.0, bug

**Comment by christopherthielen** [comment] 2016-05-13 02:58
alpha.5 is out

**Comment by inkstak** [comment] 2016-05-13 07:53
Thanks, it works just fine !
