### ISSUE TITLE
DOM Nodes Leaking

### ISSUE THREAD

**Issue by blowsie** [angular-ui/ui-router#545] opened 2013-10-31 09:22 UTC
I noticed that when using ui.router and click back and forth between pages the DOM Node Count continues to go up and up.

Tested on the ui.router sample app.
http://angular-ui.github.io/ui-router/sample/#/

![image](https://f.cloud.github.com/assets/308572/1444647/dba6d172-420d-11e3-978d-89ce009c178d.png)

I'm trying to work out what is causing the leak, but haven't found it yet.

Any ideas?

**Comment by bugeats** [comment] 2015-03-06 23:24
+1

**Comment by Nineafterten** [comment] 2015-03-07 01:47
+1

**Comment by joaoreynolds** [comment] 2015-04-24 23:08
+1

**Comment by nateabele** [comment] 2015-04-25 16:36
For anyone having this issue try what this guy did and see if it works for you: https://github.com/angular/angular.js/issues/4864#issuecomment-50540515

**Comment by coolfeature** [comment] 2015-05-14 13:27
+1

**Comment by LeonanCarvalho** [comment] 2015-05-26 13:46
+1

**Comment by bloodlanser** [comment] 2015-05-26 14:00
+1

**Comment by ruionwriting** [comment] 2015-06-07 18:26
+1 same here.

**Comment by nateabele** [comment] 2015-06-10 00:34
@LeonanCarvalho Do you use animations or animated transitions in your app?

**Comment by bugeats** [comment] 2015-06-10 00:59
@nateabele back when I was trying to diagnose the issue I did notice that ng-animate would affect the leak, but removing ng-animate completely didn't solve the problem.

**Comment by LeonanCarvalho** [comment] 2015-06-18 20:09
@nateabele  Just a "loading" page fading every state change.

**Comment by nateabele** [comment] 2015-06-22 16:55
@LeonanCarvalho Can you post a plunkr that reliably demonstrates the leak?

**Comment by LeonanCarvalho** [comment] 2015-06-23 12:05
I Tryed reproduce, but its a Large SPA, more than 200 controllers in 40 modules and 40 directives, services and factyories, but its so hard to do on Plunkr(and I can't expose all application). So I made a lite version : 

http://plnkr.co/edit/s7uZmCEKwHx4YgnmonI4?p=preview

After some navigations Is possible see the leak, on every state change the memory usage is growing and growing.

![image](https://cloud.githubusercontent.com/assets/3593706/8305574/ce748e48-1986-11e5-8de6-6504de080737.png)


I taked care about to $destroy my stuffs on every state change, but I think there something more to do.

**Comment by arjunasuresh3** [comment] 2015-07-14 11:37
+1

**Comment by eddiemonge** [comment] 2015-08-03 21:44
This seems like it more a bug in AngularJS rather than ui-router. Can someone confirm that is the case? If so, we can close this. If not, I wonder if it exists in the new [feature-1.0 branch](https://gist.github.com/eddiemonge/f9f8cb0a9dc7f42515db) that is in development

**Comment by bloodlanser** [comment] 2015-08-04 13:34
@eddiemonge As for me, the new version of ui-router resolves any memory leaks. We're waiting for release.

**Comment by eddiemonge** [comment] 2015-08-04 18:23
I am going to close this unless someone can confirm it still exists and is directly caused by ui-router.

**Comment by blowsie** [comment] 2015-08-06 11:08
@eddiemonge  I can confirm it still exists.

Test result from today using the following test;
https://github.com/angular-ui/ui-router/issues/545#issuecomment-27497815

![image](https://cloud.githubusercontent.com/assets/308572/9110155/484aee50-3c33-11e5-8f13-155e80e92fde.png)

**Comment by blowsie** [comment] 2015-08-06 11:18
Here is a test result using the same test code with angulars route provider
![image](https://cloud.githubusercontent.com/assets/308572/9110380/2b3105be-3c35-11e5-9294-a7a5a22336ea.png)

http://plnkr.co/edit/tsSRzfnnqFZ4JBkCCDfn?p=preview

**Comment by blowsie** [comment] 2015-08-06 11:19
Please reconsider your decision to promptly close this ticket. As far as I can see, it is still an issue.

**Comment by eddiemonge** [comment] 2015-08-06 18:36
@blowsie have you tested using the new branch? https://gist.github.com/eddiemonge/f9f8cb0a9dc7f42515db

**Comment by audotto** [comment] 2015-08-10 17:25
+1

**Comment by GulinSS** [comment] 2015-08-10 17:31
+1

**Comment by iltaen** [comment] 2015-08-10 17:33
+1

**Comment by bambriy** [comment] 2015-08-10 17:34
+1

**Comment by blowsie** [comment] 2015-08-11 07:04
@eddiemonge I will test on the latest branch this week

**Comment by neesonqk** [comment] 2015-08-11 14:17
+1

**Comment by nateabele** [comment] 2015-08-12 02:06
I'm glad there's so much interest in this ticket! Maybe one of you has time to dig into why this is happening. :wink:

**Comment by cndreiter** [comment] 2015-08-21 23:19
+1

**Comment by cndreiter** [comment] 2015-08-23 10:44
If I do not nest controllers inside `ui-view` using `ng-controller`, I get better performance results.

**Comment by blowsie** [comment] 2015-08-25 07:06
@eddiemonge 

**Great news;**
Results from recent testing are showing significant improvement.

![image](https://cloud.githubusercontent.com/assets/308572/9460653/2cc79c7e-4b00-11e5-9a3b-d3e8a945ce0f.png)

I would like to continue to do some further tests.

**Comment by gc23** [comment] 2015-10-13 14:52
This issue persists in  angular 1.4.7 and chrome 45. 

You can also reproduce this in the sample project http://angular-ui.github.io/ui-router/sample/#/ while running multiple times the state reload function i.e. 

`angular.element(document).injector().get('$state').reload()`

Now due to the small content on the project you'll see a small leak (~0.1MB) while having detached DOM div element the one that has ui-view. 

![screen shot 2015-10-13 at 3 50 26 p m](https://cloud.githubusercontent.com/assets/6403875/10458341/45f31f5a-71c2-11e5-9cc7-8529fbc00cbd.png)

**Comment by vasiokos** [comment] 2015-11-27 13:53
I have the same issue in a large scale application,and the leak is measure  in a range of  0.1MB up to 0.5MB (depending on state data).This can be reproduced in angular 1.4.8 and chrome 45.

**Comment by livesankp** [comment] 2016-01-08 18:02
Is this ever get resolved ? I have very large angular application which is using angular 1.4.8 and ui-router 0.2.11

I have login page when it loaded in dom i have very small amount of detached nodes.
![image](https://cloud.githubusercontent.com/assets/13769236/12205286/52d5a234-b5ff-11e5-9a72-a719c7e8ea01.png)

But if i go to one test blank page from login page which only have one button on it. 
I can see so many detached nodes. 
![image](https://cloud.githubusercontent.com/assets/13769236/12205300/77147f44-b5ff-11e5-871c-1098a0dc05a0.png)

This issue is growing when i visit my actual screens which is loading data and other controls.

I get any solution for first problem of login screen it self then i can make the same for other screens as well. Is ui-router it self have any problem or angular ?

**Comment by pratikf** [comment] 2016-04-13 17:16
I have a huge application with lots of pages, lots of controllers, similar to other people in this thread. I investigated this issue and actually found a potential problem.

I had to create a test page to isolate the issue, but I noticed that bootstrap's popover was consistently causing leaks. I updated to their latest version, and added $on('$destroy') handler, and called element.popover('destroy'), but that didn't seem to avoid the leaks, which was surprising. I put a breakpoint on that handler, and noticed that element.data() did not contain any data for the popover (it should contain one called "bs.popover"), so there was nothing to destroy, it was already leaked at that point.

After hours of stack tracing, multiple breakpoints, etc., I found that inside the ui-view directive, the cleanupLastView() function is actually removing the element before calling $destroy on the scope. This is dangerous:
http://www.bennadel.com/blog/2706-always-trigger-the-destroy-event-before-removing-elements-in-angularjs-directives.htm

There is actually 2 places where the element is attempted to be removed, first is in renderer.leave(), and second is the actual call to .remove(), which is a fallback.

The scope and child scopes should be given an opportunity to destroy themselves before the element is removed, because removing the element effectively removes all jQuery data, and any plugins can't find their data, which might be needed to actually do additional cleanup.

If you see Angular ng-view's code, they fixed this at some point:
https://github.com/angular/angular.js/blob/master/src/ngRoute/directive/ngView.js
[find cleanupLastView() - notice that scope.$destroy() is called before any .leave() or .remove() calls]
https://github.com/angular/angular.js/issues/7606

**Comment by pratikf** [comment] 2016-04-15 23:04
Plunker to demonstrate this:
http://plnkr.co/edit/AQbId6GFcpiIXDYUpaGi

**Comment by joehany** [comment] 2016-04-19 15:08
+1

**Comment by rpocklin** [comment] 2016-04-21 06:24
When we upgraded to 0.2.18 from 0.2.15 we saw this issue.  We are not performing animated state changes and found ui-router doesn't clean up the old `<div ui-view>` elements but keeps appending over time (the remove and destroy handlers weren't being called).

Looks like the code in the function `cleanupLastView()` is buggy or not working as intended.

Adding the attribute `noanimation="true"` to our `<div ui-view>` element works around the problem for now (reverts the view lifecycle behaviour)

**Comment by pocesar** [comment] 2016-05-08 17:55
I'm seeing this as well, I have a mid-sized app that uses only ui-router for the navigation, and when doing development, I need to restart the browser from time to time because the leak is really bad (1.6GB up from 400MBish)

**Comment by gwely** [comment] 2016-05-19 18:52
I'm seeing this issue with ui-router 0.2.18 and 0.2.17. I also tried adding `noanimation="true"` to the `<div ui-view>`. @rpocklin you were not experiencing this issue with 0.2.15?

Here is a timeline of just switching back and forth between states. The large drop in listeners is a manual garbage collection.

![image](https://cloud.githubusercontent.com/assets/1675806/15405761/4a946fe4-1dd1-11e6-9f91-18dac5c1a4a3.png)

**Comment by blowsie** [comment] 2016-05-20 10:42
Can we please remove the awaiting response tag from the ticket?

**Comment by anmarcek** [comment] 2016-06-07 13:43
+1

**Comment by sebaplaza** [comment] 2016-06-09 09:34
+1

**Comment by kareniel** [comment] 2016-06-17 17:40
without noanimation=true:
![before](https://cloud.githubusercontent.com/assets/419946/16159458/e1f198a0-3490-11e6-802d-89aba3849803.png)

with noanimation=true:
![after](https://cloud.githubusercontent.com/assets/419946/16159461/e5b7cfb8-3490-11e6-921d-a70bdc89d8f4.png)

**Comment by Olgagr** [comment] 2016-06-24 19:28
I noticed huge amount of detached DOM trees when navigating between nested states. My state structure looks like this:

```
  $stateProvider
     .state('app': {templateUrl: 'app.html'})
     .state('app.home', {abstract: true, templateUrl: 'home.html'})
     .state('app.home.publications', {...})
     .state('app.home.publications.plan', {
         views: { "@app.home": {....} }
     }),
     .state('app.home.publications.plan.editor', {
         views: { "@app.home": {....} }
     })
```

and views: app.html:

```
<ui-view></ui-view>
```

home.html:

```
<div class="home-content">
  <ng-include src="'/src/app/app_header.html'"></ng-include>
  <div>
    <ui-view></ui-view>
  </div>
</div>
```

The default state that user is redirected is app.home.publications. Every time when I navigates between app.home.publications and app.home.publications.plan I can see in the Chrome profiler that the whole view for app.home.publications state becomes detached DOM tree!

<img width="526" alt="twipe_publishing_tools" src="https://cloud.githubusercontent.com/assets/1297219/16348162/395d5c3a-3a51-11e6-82fe-b2f20f637768.png">

If user navigates between these two states for example 3 times in the row, I have 3 copies of detached DOM tree of state app.home.publications.

<img width="492" alt="twipe_publishing_tools" src="https://cloud.githubusercontent.com/assets/1297219/16348182/4ffa8166-3a51-11e6-8af7-b7aaed9efe3f.png">

I don't think this is expected behaviour. I understand that one copy of parent state view is kept for caching purposes but creating every time the new copy ? For me this causes huge memory leaks because app.home.publications is basic view, so user rarely go outside this state (he rather navigates to nested views). Only when user navigates to the sibling of app.home.publications state, all detached DOM trees are cleared. 

angular version: 1.5.6
ui-router: 0.3.1

**Comment by loureirorg** [comment] 2016-06-25 17:43
Not sure if it helps, but I had the same problem and in my case it was caused by jQuery. jQuery creates references to DOM elements (it's its "cache" mechanism). As browsers can't destroy objects that are still being referenced, they keep them on memory. 

In my case I solved this by hiding/showing views instead of create/destroy them.

**Comment by pocesar** [comment] 2016-06-25 19:33
@loureirorg the problem is that it happens in http://angular-ui.github.io/ui-router/sample/#/ and it doesn't use jquery

**Comment by loureirorg** [comment] 2016-06-25 20:30
@pocesar I see, but just as a curiosity on your example, the extra detached dom objects are being generated by "jqLite", which is a lite version of jQuery. Angular's jqlite also uses a cache mechanism which on your example is referencing those detached dom objects.

**Comment by loureirorg** [comment] 2016-06-25 20:48
Just a guess, but maybe this is the culprit:
https://github.com/angular/angular.js/blob/master/src/jqLite.js#L124

**Comment by Olgagr** [comment] 2016-06-26 06:27
@loureirorg I don't use jQuery in the project, but of course jqLite is there with its caching. However, if these detached trees are created because of caching, why are there 3 copies of them ? Doesn't it negate the idea of caching? Moreover, when I leave the state and for example go to sibling state, all of these detached nodes are gone. That's why I'm thinking this is something inside ui-router and not in Angular-jqLite.

**Comment by cstenac** [comment] 2016-07-18 07:00
A bit late to the game, but I thought this might be useful for future reference. The following pen produces a leak on 0.2.17 which is fixed since 0.2.18:
http://codepen.io/zorgluby/pen/LkQNpw

Click several times on the "Transition" button then take a Heap snapshot:
* In 0.2.17, you'll notice several instances of Uint8Array in the heap, indicating that the previous scopes of the ItemSubController haven't properly been destroyed
* In 0.2.18, only one instance of UInt8Array, as expected

The bug was only reproducible with a reload transition to the same state.
The extra items were still retained via the scope hierarchy because the $destroy was not being called on the previous scopes (but it's unclear for me why since the nodes seemed properly removed - I guess it might be related to the animation stuff). As far as I can see, you really need(ed) to have "deep" states for the issue to happen.

**Comment by SeeeD** [comment] 2016-08-11 15:48
+1

**Comment by toni-mota** [comment] 2016-10-28 14:45
Same memory issue with nested views in 0.2.15 and 0.2.18... any news about it?

**Comment by LeonanCarvalho** [comment] 2016-11-17 13:22
3 years and  we still have the same issues.

**Comment by smcauliffe** [comment] 2016-11-28 20:21
I just realized this is happening in one of my apps - memory increases with every state change and is never reduced. Angular 1.5.9, ui-router 0.3.2. Anyone have any idea how to work around?

**Comment by Olgagr** [comment] 2016-11-28 20:24
@smcauliffe Do you have nested states ?

**Comment by smcauliffe** [comment] 2016-11-28 20:28
@Olgagr yes

**Comment by Olgagr** [comment] 2016-11-28 20:45
@smcauliffe See above. I had the same issue. In my case the fastest solution was to remove nested states.

**Comment by smcauliffe** [comment] 2016-11-28 20:55
@Olgagr wow in a quick test that immediately solves the problem. In one app it was easy to remove nested states - another will not be :( 

Many thanks. Pretty scary stuff really.

**Comment by slawrence** [comment] 2016-12-06 21:40
Same problem. Eliminating the nested state resolved it.

**Comment by quocanhbk09** [comment] 2016-12-26 10:53
Any new on this issue?
Our project is quite big, so we got a serious problem with memory leak with continuously increasing memory when switching state. (increase about 4-5MB for each switch) we use version 0.2.18, and after updating it to 0.3.2, the issue still happends.

@slawrence Sorry for stupid question, but does "eliminating the nested state" you mentioned mean that not using nested state? or there is a way to properly clean the nested state to prevent memory leak?

Thanks

**Comment by marcoblos** [comment] 2017-01-19 20:31
@quocanhbk09 I have same issue than you and all others in this thread and I have same doubt about the slawrence response... @slawrence what did you want with "Eliminating the nested state"... How do you resolve nested states?

**Comment by henk23** [comment] 2017-01-19 20:35
@marcoblos The way I understand it is this: Do not use nested states. Try to make your app work without them. (I hope I understand it wrong, because that is not a real solution to the problem.)

**Comment by smcauliffe** [comment] 2017-01-19 20:37
Unfortunately, this seems to be the only "fix" to the problem - which is that the nested state feature is unusable. I would love to be corrected.

**Comment by marcoblos** [comment] 2017-01-19 20:44
@henk23 @smcauliffe I understood about slawrence's response, but I was really hoping I was wrong about the solution.. ;/

**Comment by zalenix** [comment] 2017-01-31 23:02
@gwely how did you solve your problem?

**Comment by enjoiful** [comment] 2017-01-31 23:25
"Don't use nested states" is an extremely crummy work around when it is advertised as a core feature of the router.  Had I known nested states would cause massive memory leaks, I would have chosen a different router.  It seems daunting for me to rewrite 100+ routes in our large app. Even worse considering the code duplication that we'll incur when "de-nesting" all states, as well as losing the thoughtful hierarchy that nested states provides.

At the very least the nested states memory leak should be advertised on the readme as busted until fixed.  Literally in the repo header: "The de-facto solution to flexible routing with nested views in AngularJS"

**Comment by christopherthielen** [comment] 2017-02-02 21:37
I'd like to officially respond to this ticket.  If there are DOM nodes leaking, UI-Router should be fixed.

So, to help reproduce this problem of leaking DOM nodes, I've created a test harness.  I've noticed that with AngularJS 1.2.27 and earlier, the DOM nodes do indeed leak.  By switching to 1.2.28+, I've been unable to reproduce leaking DOM nodes no matter what version of UI-Router I use.

![screen shot 2017-02-02 at 3 04 38 pm](https://cloud.githubusercontent.com/assets/2053478/22569163/0f3a3594-e95c-11e6-8a32-1543da9a825b.png)

![screen shot 2017-02-02 at 3 04 38 pm](https://cloud.githubusercontent.com/assets/2053478/22569214/4865d274-e95c-11e6-9b5e-a4883a41ba7d.png)

I have noticed that HEAP memory usage might increase, but not DOM nodes.  The heap increase doesn't seem to be increasing fast enough to become a problem (1-2 MB for 300 state changes)

Note that HEAP is used bay anything and everything in a web page, including user code, and things completely outside UI-Router's control such as browser URL history, etc.  An increase in HEAP usage over time might be completely normal.

-----

# A Test Harness

So, I've created a test harness for you to use. 
Reading back in this issue, I'm told the original UI-Router sample app demonstrates the issue.  So, the test harness is based on that sample app.

https://christopherthielen.github.io/ui-router-dom-leak-test/#/leaktest-instructions

The purpose of this harness is so we can all be using the same controlled environment.  However, please tweak this test harness.  Use various combinations of UI-Router and AngularJS versions.  Modify the app code.  Do whatever you need to do to trigger the leaks.  When you have reproduced the leaking DOM nodes, create a PR to my repository with instructions, and respond here.


# Garbage Collection

*You must run garbage collection at the beginning and end of any test run.*  While a single state change might take 5 MB of heap, that memory should be reclaimed by garbage collection.  Normally, it's up to the browser to initiate garbage collection.  The browser may choose to delay a full GC for a very long time, and the results might be very misleading.  By running GC at the beginning and end of any test run, we can normalize the actual heap memory and nodes in use.

**Comment by christopherthielen** [comment] 2017-02-02 22:18
Interestingly, when I use Chrome Canary, I always show leaking nodes

![screen shot 2017-02-02 at 4 16 51 pm](https://cloud.githubusercontent.com/assets/2053478/22570953/344ebb3c-e963-11e6-91f3-4b87f2829eb3.png)

**Comment by coolfeature** [comment] 2017-02-04 11:37
This thread is long and I have not read it all but I thought I would share what I had to do in my Ionic app to make sure my scopes are cleaned up on state change. 

I noticed $destroy event is not fired in my controller attached to an abstract state:

```
        .state('a-1', {
		url: '/a-1'
		, abstract: true
		, cache: false
		, templateUrl: 'views/a-1.html'
		, controller: 'A1Controller'
	})
```

I had to do the following to make sure the scope is cleaned up properly:

```
    $scope.$on("$ionicView.beforeLeave", function(event, data){
        if (data.abstractView === true) {
            $scope.$destroy();
        }
   });
```

Hope this helps.

**Comment by dacsy** [comment] 2017-10-12 03:34
Hi all
I am running in to this issues for my old application, my application have been built and release for a few years since 2014. We are having the same problem with angular 1.2.15 and ui-router 0.2.13
I have been researching and reading this topic, but finally could not find the final version should I upgrade to solve the problem.
@christopherthielen mentions angular 1.2.28+ and ui-router 0.4.2 it also a big change for me to upgrade to this version cause the old application and quite big also.
Is anyone have other idea can help to solve my problem ? Thank you

**Comment by peebeebee** [comment] 2017-11-06 10:29
We are experiencing a lot of detached dom nodes on @uirouter/angularjs@10.0.10 with nested views.

**Comment by christopherthielen** [comment] 2017-11-09 04:10
This issue is closed because I have seen no evidence of DOM nodes leaking.  If you have evidence, please post the evidence.

**Closed** 2017-11-09 04:09 UTC
Labels: bug, maybe, meta

**Comment by blowsie** [comment] 2017-11-09 11:58
@christopherthielen what about your own evidence? What are you referring to here?

**Comment by peebeebee** [comment] 2017-11-09 12:37
I posted here that there was a problem with UI-Router, but it was another internal library that was causing it. Sorry @christopherthielen  :)
