### ISSUE TITLE
In 0.2.14 $state.go not work if we have bool and object in params.

### ISSUE THREAD

**Issue by Boychenko** [angular-ui/ui-router#1943] opened 2015-05-06 06:40 UTC
Hi [Plunker](http://plnkr.co/edit/OcLxTBmHbYfxtw1sJJih?p=preview) with issue.
It not throw any error just not working. In 0.2.13 this worked well

**Comment by eddiemonge** [comment] 2015-05-06 17:47
duplicate of #1915

**Closed** 2015-05-12 18:30 UTC
