### ISSUE TITLE
$destroy event is triggered on leaving view before animation/transition ends

### ISSUE THREAD

**Issue by ghoullier** [angular-ui/ui-router#1643] opened 2014-12-18 09:52 UTC
When animations are associated to a view using ngAnimate, $destroy event is triggered on leaving view before animation/transition ends.

This event should be triggered after animation/transition end?

[Plunker](http://plnkr.co/edit/UQcrIpf2V44pXTROQmVm?p=preview)

angular@1.3.6
angular-animate@1.3.6
ui-router@0.2.13

**Comment by Roman-Didenko** [comment] 2015-03-22 14:22
+1

**Comment by philBrown** [comment] 2015-04-01 04:33
This is because this part in `cleanupLastView()` doesn't wait for the `renderer.leave` promise

    if (currentScope) {
        currentScope.$destroy();
        currentScope = null;
    }

**Comment by nateabele** [comment] 2015-04-01 06:41
Okay, so, I guess it should?

**Comment by philBrown** [comment] 2015-04-28 00:44
@nateabele yes, because until the animation completes, the *leaving* state's scope is still relevant.

For example, I have an Highcharts chart in my view (using `highcharts-ng`). When I transition to another state via an animation, the chart is destroyed (and removed from the DOM) before the animation completes.

**Comment by nateabele** [comment] 2015-04-28 01:49
Well, I'll patch it as soon as I can, unless you think you can [do it faster](https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md).

**Comment by manro** [comment] 2015-09-13 09:54
I think this code change would help:

Current cleanupLastView function:
```javascript
function cleanupLastView() {
  if (previousEl) {
    previousEl.remove();
    previousEl = null;
  }

  if (currentScope) {
    currentScope.$destroy();
    currentScope = null;
  }

  if (currentEl) {
    renderer.leave(currentEl, function() {
      previousEl = null;
    });

    previousEl = currentEl;
    currentEl = null;
  }
}
```


cleanupLastView function with deferred animate-out element scope destroy:
```javascript
function cleanupLastView() {
  if (currentEl) {
      (function(previousEl, currentScope) {
          renderer.leave(currentEl, function() {
              if (previousEl) {
                  previousEl.remove();
                  previousEl = null;
              }
              if (currentScope) {
                  currentScope.$destroy();
                  currentScope = null;
               }

               previousEl = null;
               currentScope = null;
          });
      })(previousEl, currentScope);
  } else {
      if (previousEl) {
          previousEl.remove();
          previousEl = null;
      }
      if (currentScope) {
          currentScope.$destroy();
          currentScope = null;
      }
  }
  previousEl = currentEl;
  currentEl = null;
}
```

**Comment by nateabele** [comment] 2015-09-14 17:25
Great. PR + unit test?

**Comment by SmuliS** [comment] 2015-10-30 13:06
@nateabele Ping. Now there is a PR open with tests. This is a very welcome PR if you have state change animations!

**Comment by nateabele** [comment] 2015-10-30 14:02
@SmuliS Merged.

**Closed** 2015-10-30 14:01 UTC

**Comment by ghoullier** [comment] 2015-10-31 19:22
:+1:

**Comment by petermolyneux** [comment] 2015-11-10 12:49
This fix worked for some of our situations, but made it worse for others.

The problem for us is when we have a Kendo grid on a page with a base page. When leaving the page we get an error something like "Can't set property template of null". Before the fix we got the error only if the grid was in a template for a component with transclude. Now it works fine in that situation, but we get the same error when our routing is set up to use base pages.

I think the problem with the fix is that we now don't control the order things are removed/destroyed in. 

I.e. If a scope has a child scope and the child contains animations, the parent will try to broadcast destroy before the child is ready.

I hacked the code to get it to work. Basically what I do is wait for all elements to report there leave-events and then do a cleanup for all of them at once.

The code might help you understand the issue and find a good solution:
```javascript
function cleanupLastView() {
    var _currentEl;
    var i = 0;

    if (currentScope) {
        currentScope._willBeDestroyed = true;
    }

    function cleanOld(prevEl, currScope) {
        if (prevEl) {
            prevEl.remove();
        }

        if (currScope) {
            try {
                currScope.$destroy();
            } catch (e) {
                currScope.$destroy();
            }
        }
    }

    if (currentEl) {
        awaitingCleanup.push({ prevEl: previousEl, currScope: currentScope, currEl: currentEl, readyForRemoval: false });
        _currentEl = currentEl;
        renderer.leave(_currentEl, function () {
            var allReady = true;
            for (i = 0; i < awaitingCleanup.length; i++) {
                if (awaitingCleanup[i].currEl === _currentEl) {
                    awaitingCleanup[i].readyForRemoval = true;
                }
                allReady = allReady && awaitingCleanup[i].readyForRemoval;
            }
            if (allReady) {
                while (awaitingCleanup.length > 0) {
                    cleanOld(awaitingCleanup[awaitingCleanup.length - 1].prevEl, awaitingCleanup[cleanUpOrder.length - 1].currScope);
                    awaitingCleanup.pop();
                }
            }
            previousEl = null;
        });

        previousEl = currentEl;
    } else {
        cleanOld(previousEl, currentScope);
        previousEl = null;
    }

    currentEl = null;
    currentScope = null;
}

```

Hope this help,

Peter Molyneux

**Comment by christopherthielen** [comment] 2016-02-15 16:58
@petermolyneux I'd like to understand your use case better.

Please explain your setup.
- ui-views
- animations
- how do you utilize `$destroy`

If we expose the animation promise, will you be able to clean your resources using that promise, instead of $on($destroy)?

**Comment by christopherthielen** [comment] 2016-03-01 02:37
We will be reverting this change in favor of exposing the animation promise #2562

**Comment by dmitry-dedukhin** [comment] 2016-03-25 10:37
https://github.com/angular-ui/ui-router/issues/2614
Another terrible issue caused by this change.
