### ISSUE TITLE
Controllers are reloaded, after a previous use of {notify: false}

### ISSUE THREAD

**Issue by dhavyd** [angular-ui/ui-router#2409] opened 2015-12-03 10:41 UTC
UI-Router 0.2.15

This can be related to https://github.com/angular-ui/ui-router/issues/1387

I have the following states:
```
  var appState = {
    name: 'app',
    url: "/:view?from&to&selected&filter",
    views: {
      'header@': {
        controller: 'HeaderCtrl',
        templateUrl: '/headet.html',
      },
      'content@': {
        controller: 'ContentCtrl',
        templateUrl: '/content.html'
      }
    };
  var searchState = {
    name: 'app.search',
    url: "/search?query",
    views: {
      'sidebar@': {
        controller: 'SearchCtrl',
        templateUrl: '/search.html'
      }
    },
 };
```
If I call
```
$state.go($state.$current, {view: 'table'}, {notify: false});
```
it updates the "view" parameter as expected without reloading HeaderCtrl or ContentCtrl. But if I, after that call
```
$state.go('app.search', {query: 'mykeyword'});
```
Then both HeaderCtrl and ContentCtrl are reloaded (including the views). I don't use "{notify: false}" in the first call, then the controllers are reloaded in the first call, but not in the second one.

I need to update "view" on "app" state with reloading everything and then be able to call "app.search" without reloading HeaderCtrl and ContentCtrl, why I used "{notify: false}" on the first call. I don't want to reload these controllers at all.

Thanks for any help!

**Comment by eddiemonge** [comment] 2015-12-03 19:56
This is a duplicate of a few other issues. notify false is full of problems and is being reworked/removed. Lets say duplicate of https://github.com/angular-ui/ui-router/issues/1674

**Closed by eddiemonge** 2015-12-03 19:56 UTC
