### ISSUE TITLE
Is it possible to switch off inheritance in `resolve` load?

### ISSUE THREAD

**Issue by extempl** [angular-ui/ui-router#2787] opened 2016-06-02 17:10 UTC
Imagine you have page with list of items, and nested page with item - in both of them there are data loading in resolve. And when you open item page - it will resolve list of items as well. Why? I do not want it to behave like this.

**Comment by christopherthielen** [comment] 2016-06-02 17:25
By design, if a state is activated, its parent states are also activated. All resolve data for all activated states are fetched.

Perhaps you could use siblings states instead of nested states?

**Comment by christopherthielen** [comment] 2016-06-03 19:47
closing because this is as design

**Closed by christopherthielen** 2016-06-03 19:47 UTC
