### ISSUE TITLE
same controller and state is reloaded after using $state.go then trying to navigate to a new state 

### ISSUE THREAD

**Issue by btm1** [angular-ui/ui-router#2140] opened 2015-07-29 20:44 UTC
If you use $state.go($state.current.name,params,{notify:false, reload:false, location:'replace', inherit:true}) to change the URL params without reloading the current state .... and then you click another link ( i.e. #/somenewstate/somepage?blah=1) the same controller and same state that you are currently on just gets reloaded (sometimes with the original params before you had used $state.go to change them).

Does anyone have a fix for this or know of a way to stop it from doing this? Is this a known issue?

**Comment by eddiemonge** [comment] 2015-07-29 21:32
duplicate of #1673

**Closed by eddiemonge** 2015-07-29 21:32 UTC
