### ISSUE TITLE
Syntax error, unrecognized expression: #/...

### ISSUE THREAD

**Issue by edamron** [angular-ui/ui-router#1423] opened 2014-10-03 17:58 UTC
I recently started getting these errors when I click on a ui-sref link, EVEN THOUGH it still takes me to the given state / templateUrl.  Here's a small snippet from my app.js file:

            .state('prepare', {
                abtract: true,
                url: '/prepare',
                templateUrl: 'prepare/prepare.html',
                controller: 'prepareController'
            })
                .state('prepare.propinss', {
                    url: '/propinss',
                    templateUrl: 'prepare/question.html'
                })

The abstract state ('prepare') doesn't cause an error to be recorded in the log, but the 'prepare.propinss' state does cause it:

Uncaught Error: Syntax error, unrecognized expression: #/prepare/propinss

BTW, the actual error itself comes from jquery.js:1437 (Sizzle.error = func...).

It seems I can safely ignore this error, but I'd prefer to eliminate it, just in case it does eventually cause me a real issue.

Thanks!

**Comment by skannan74** [comment] 2015-01-14 05:14
i too had the same issue and after few hours stuggle, i found out 
i had something like this in the navigation bar. i just removed data-toggle="collapse" and problem solved.
 <a class="accordion-toggle collapsed " data-toggle="collapse" ui-sref="user">

**Comment by stwiname** [comment] 2015-01-15 19:56
Removing uses of data-toggle with ui-sref solved the issue for me

**Comment by sulmanen** [comment] 2015-02-16 14:44
@stwiname thnx worked beautifully. so fixed by removing data-toggle="tab"

**Comment by renesansz** [comment] 2015-02-19 14:26
+1
Having also issues with v0.2.13

@stwiname's fix works, but I don't want to remove the data-toggle="collapse" because I need it.

**Comment by rajesh38** [comment] 2015-05-07 07:15
@stwiname  (y)

**Comment by gauravkhullar1690** [comment] 2015-05-13 10:15
worked for me as well thanks

**Comment by VegaFromLyra** [comment] 2015-07-17 16:45
I am on v0.2.11 and I was seeing the same error with a ui-sref tag that was used along with `data-toggle="tab"`, though not sure why the `data-toggle` was added in the first place. Removing it as pointed out in this post helped fix the problem.

**Comment by eddiemonge** [comment] 2015-08-18 21:03
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Closed by eddiemonge** 2015-08-18 21:03 UTC
Labels: PlunkrPlease

**Comment by SeregaSh** [comment] 2015-10-06 17:33
Had the same problem. Check here - http://stackoverflow.com/questions/16785264/jquery-syntax-error. No need to delete the data-toggle. The problem is in '/' in hrefs (I had nested states and url for parent state, so I had url "#/parent_state_url/child_state_url" and I was getting the issue because of "/". I deleted url for parent state and it works.). Hope this helped.

**Comment by jitendersandhu** [comment] 2016-01-13 19:28
I also faced the same issue with `ui-sref`, removing `data-toggle="modal"` solved it.
@skannan74 Thanks for the fix!

**Comment by shreyasBhargava** [comment] 2016-04-23 06:44
@skannan74  thank it works

**Comment by s1lviu** [comment] 2016-12-04 15:28
If you use bootstrap, remove the "nav" class:
<img src="https://i.imgur.com/rFVEbgi.png">

**Comment by muratgucuk** [comment] 2017-12-27 19:19
@skannan74 thanks its working for me.

**Comment by pc-trent** [comment] 2019-01-04 03:43
Is there an actual fix to this? I hardly see how stripping out functionality is an appropriate resolution to this.
