### ISSUE TITLE
reload() doesn't resolve templates

### ISSUE THREAD

**Issue by ribizli** [angular-ui/ui-router#751] opened 2014-01-10 10:29 UTC
I've have a scenario to reload state if the user changes language. The language is changed on server side, so the templates are translated by the server (using a lang parameter or a session value for the language).

I've created a languageTemplateProvider function (used in `state.templateProvider`) like this:

``` javascript
function($http, $templateCache, languageService) {
    var langUrl = url + '?lang=' + languageService.selectedLanguage;
    return $http.get(langUrl, { cache: $templateCache })
        .then(function(response) { return response.data; });
}
```

On language change I clear the `$templateCache` so the template is re-downloaded from the server correctly.

But here comes the **possible BUG**: the state reloads/resolves before the `$http` finishes with the old template. Why?

On normal state change, the change happens only after the templates are correctly downloaded, so it seems correct (simulated with `$timeout`).

Sorry that I cannot provide a _plunkr_, but my app is already very complex to extract the needed components...

**Comment by christopherthielen** [comment] 2017-05-03 17:34
Closing because this is really really old, the plunker link doesn't work, and I think this is fixed in 1.0 codebase.  Please reopen if the issue is still valid.

**Closed by christopherthielen** 2017-05-03 17:34 UTC
Labels: bug
