### ISSUE TITLE
Lazy Loading a module which has some syntax error will crash browser

### ISSUE THREAD

**Issue by zhoujianhui** [angular-ui/ui-router#3557] opened 2017-11-08 15:17 UTC
This is a:

- [ x ] Bug Report
- [ ] Feature Request
- [ ] General Query 

My version of UI-Router is: (version)
v1.0.10

# Bug Report
Lazy loading a module which has some syntax error will crash browser.
In lazyload.ts
```javascript
function updateStateRegistry(result) {
        if (result && Array.isArray(result.states)) {
            result.states.forEach(function (state) { return transition.router.stateRegistry.register(state); });
        }
        return result;
```
if module has error, the result is not **Promise\<LazyLoadResult\>**, browser will be freezed then crash!!!

**Comment by zhoujianhui** [comment] 2017-11-08 18:30
I fix that like this
```javascript
function updateStateRegistry(result) {
            if (!transition.router.stateRegistry.states[result]) {
                throw new Error(result + ' not loaded');
            }

            if (result && Array.isArray(result.states)) {
                result.states.forEach(function (state) {
                    return transition.router.stateRegistry.register(state);
                });
            }
            return result;
        }
```
By the way I use Angularjs 1.6.6 + ocLazyload. ocLazyload success load a module but it has error, so states will not be registry successfully. updateStateRegistry method should check it.

**Comment by zhoujianhui** [comment] 2017-11-08 18:30
I fix that like this
```javascript
function updateStateRegistry(result) {
            if (!transition.router.stateRegistry.states[result]) {
                throw new Error(result + ' not loaded');
            }

            if (result && Array.isArray(result.states)) {
                result.states.forEach(function (state) {
                    return transition.router.stateRegistry.register(state);
                });
            }
            return result;
        }
```
By the way I use Angularjs 1.6.6 + ocLazyload. ocLazyload success load a module but it has error, so states will not be registry successfully. updateStateRegistry method should check it.

**Comment by zhoujianhui** [comment] 2017-11-08 18:30
I fix that like this
```javascript
function updateStateRegistry(result) {
            if (!transition.router.stateRegistry.states[result]) {
                throw new Error(result + ' not loaded');
            }

            if (result && Array.isArray(result.states)) {
                result.states.forEach(function (state) {
                    return transition.router.stateRegistry.register(state);
                });
            }
            return result;
        }
```
By the way I use Angularjs 1.6.6 + ocLazyload. ocLazyload success load a module but it has error, so states will not be registry successfully. updateStateRegistry method should check it.

**Comment by christopherthielen** [comment] 2017-11-13 03:22
`updateStateRegistry` shouldn't be called if there's an error.  The value returned by ocLazyLoad should be a rejected promise which should then trigger the error handler:

```
    promise = lazyLoadFn['_promise'] =
        services.$q.when(lazyLoadFn(transition, state))
            .then(updateStateRegistry)
            .then(success, error);
 ```

Can you show how it fails in a plunker or stackblitz?

**Comment by zhoujianhui** [comment] 2017-11-14 01:43
I use browser-sync to live reload angularjs app. If I have a unfinished route js file which has syntax error, the browser will reload then crash.

**Comment by christopherthielen** [comment] 2017-12-20 04:53
Closing because there is no reproduction provided. Provide some way that I can replicate this (preferably stackblitz or plunker) and we can re-open this.

**Closed by christopherthielen** 2017-12-20 04:53 UTC
Labels: PlunkrPlease
