### ISSUE TITLE
$stateParams not having the same content that $state.$params

### ISSUE THREAD

**Issue by tykayn** [angular-ui/ui-router#2211] opened 2015-08-26 14:38 UTC
i am not sure that is an issue, but i am surprised that $stateParams is not containing the same params between parent and child controller, as i would expect in any inheritance.

i have a ParentRoute, with a ParentController.
i speciefed a child route, with a ChildController.

$state.$params (called in the ChildController) contains all the parameters of both controllers,
but $stateParams seems to contain only the children parameters. how weird

**Comment by eddiemonge** [comment] 2015-08-26 18:52
duplicate of a few other tickets.

**Comment by eddiemonge** [comment] 2015-08-26 18:52
https://github.com/angular-ui/ui-router/issues/2076
https://github.com/angular-ui/ui-router/issues/1984
https://github.com/angular-ui/ui-router/issues/136

**Closed by eddiemonge** 2015-08-26 18:52 UTC
Labels: duplicate
