### ISSUE TITLE
parent state reloaded when $state.go to child state

### ISSUE THREAD

**Issue by aestheticsdata** [angular-ui/ui-router#3316] opened 2017-02-03 14:05 UTC
in my code, app is the parent state of questions. When clicking prev or next on the nav $state.go('questions') is executed, but the parent state app is reloaded too, and I don't want to reload the parent state.
Is it a correct behavior of ui-router ?

I have the same problem that #3297 but there is no answer.

**Comment by Slumber86** [comment] 2017-02-15 11:59
Same here! which version are you using?

**Comment by christopherthielen** [comment] 2017-02-17 16:47
Can you show code? A plunker demo would help.

**Comment by Slumber86** [comment] 2017-02-17 17:24
we have tried to make a reproduce using the demo app, but the issue is not showing, working on it, we keep posted

**Comment by christopherthielen** [comment] 2017-03-14 16:14
states are reloaded in the following cases:

- a parameter value belonging to the state changed
- a parameter value belonging to a parent state changed
- The `reload` option is being used

Please post a reproduction and I'll take a look.  In the meantime, I'm closing to reduce clutter.

http://UIR-Plunk

**Closed by christopherthielen** 2017-03-14 16:14 UTC
Labels: PlunkrPlease
