### ISSUE TITLE
Previous states' controllers are executing in current state 

### ISSUE THREAD

**Issue by GeniusGo** [angular-ui/ui-router#3242] opened 2017-01-04 07:15 UTC
Hi all,
   I'm using angular 1.5.8 and ui-router v0.2.11. I have configured all the routing in app.js. and added all the controllers' reference in index.html file.
  The problem I'm getting is when a state is changed, previous state's controller is being loaded in the current page. So the Restangular API call previous is executing in the current page on state load and also on scroll (as next API call are configured on scroll). It is breaking our functionality.
   I have tried $state.reload(), but it also didn't work. **But reloading a page works as expected.** 
   I want only the controller of current state should be executed and other controllers should be unbound for current state.

**Comment by anantanandgupta** [comment] 2017-01-04 12:23
will it be possible to update to 0.3.x and test?

**Comment by christopherthielen** [comment] 2017-01-07 22:38
Please update to a recent version and retest. If it still doesn't work, please create a plunker that demonstrates how to reproduce the issue.

http://bit.ly/UIR-Plunk

**Comment by IzakK** [comment] 2017-01-19 09:52
Hi, I have a similar issue in which the previous states' controller is being loaded first before transitioning to new state. Am I perhaps doing something wrong? Please open developer console in below plunker. Once open, click on the "Go to more bleh" button and then click on the Meh tab. Looking in the console you'll see the moreBleh's controller instance get's loaded again before completing the transition to the new bleh state controller.

https://plnkr.co/edit/HvFNHopTvGtr3kXHAi4M?p=preview

**Comment by christopherthielen** [comment] 2017-01-21 21:00
@IzakK your problem is due to an interaction between the way ui-bootstrap  and ui-router work.  As far as ui-router is concerned, this is expected behavior.

When you click the tab, ui-bootstrap re-renders the tab contents.  The contents includes a `ui-view` so it links a new `ui-view`.   The `ui-view` is then loading the controller for the current state (which targets the ui-view).

I think that's what's happening, at least.

---

I haven't found that ui-bootstrap's tabsets to play nicely with ui-router states and generally just use the bootstrap markup, ui-sref, and a single ui-view to do my tab implementations.


---

I'm closing this issue because the original reporter hasn't responded, and I think your issue  "works as designed" as far as I can tell.  If you are certain there's an issue with ui-router, feel free to open a new issue.

**Closed by christopherthielen** 2017-01-21 21:00 UTC
Labels: PlunkrPlease
