### ISSUE TITLE
with html5 enabled mode - Showing apache directory

### ISSUE THREAD

**Issue by cullsin** [angular-ui/ui-router#2735] opened 2016-05-09 23:32 UTC
Hi, 

I did the following and it works with index.html. However if I refresh it shows the apache 
default Index Page. Please correct me what I missed.  

Clearly,

http://anaoh.com/home  -- opens the apache directory index while refreshing .. [ Issue ]

In the App, 

       app.config(["$locationProvider", function($locationProvider) {
	       $locationProvider.html5Mode({
	 	   enabled: true
              });
       }]);

In the Apache
      <Directory /base/app/>
    RewriteEngine on

    # Don't rewrite files or directories
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]

    # Rewrite everything else to index.html to allow html5 state links
    RewriteRule ^ index.html [L]
        </Directory>

In the html, 
     <base href="/app/ui/">

Thanks,
Raja K

**Comment by eddiemonge** [comment] 2016-05-12 17:36
please ask this in stackoverflow. also a duplicate of your other one. You probably need `/index.html`

**Closed by eddiemonge** 2016-05-12 17:36 UTC

**Comment by cullsin** [comment] 2016-05-22 20:55
Hi, 

It's working fine. Sorry I did a wrong init in home page. Thanks.

Raja K
