### ISSUE TITLE
Redirect loop on state with errored resolve

### ISSUE THREAD

**Issue by andyrooger** [angular-ui/ui-router#1022] opened 2014-04-11 13:45 UTC
In our code we are using the code in the faq for [optional trailing slashes](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes). We also have a number of states loading data using the `resolve` attribute.

I observe the following four cases when navigating to states that use `resolve`, both from other states, and when navigated to directly by URL:

Navigate from      | Data successfully resolved         | Data resolution failed
----------------------|------------------------------------------|----------------------------
Another state      | Ends at expected state and url    | Stays on (or is returned to) original state and url
Another website  | Ends at expected state and url    | URL remains that of the failed state, but the actual state is '' or the abstract root state

If we then include the redirection for trailing slashes in the FAQ, and navigate to the same states but without a trailing / then all of these cases other than the bottom right remain the same.

When navigating directly to a state whose resolution fails, we get into a loop where the redirect adds a /, starting a transition to the state, the state then fails during its resolve and redirects back to the address without a /. This loop continues flipping the / back and forth until we receive the following two 'infinite digest' errors.

```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 7; oldVal: 6"],["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldVal: 8"],["fn: $locationWatch; newVal: 10; oldVal: 9"],["fn: $locationWatch; newVal: 11; oldVal: 10"]]
http://errors.angularjs.org/1.2.15/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3…2fn%3A%20%24locationWatch%3B%20newVal%3A%2011%3B%20oldVal%3A%2010%22%5D%5D
    at http://code.angularjs.org/1.2.15/angular.js:78:12
    at Scope.$digest (http://code.angularjs.org/1.2.15/angular.js:12070:19)
    at Scope.$apply (http://code.angularjs.org/1.2.15/angular.js:12279:24)
    at http://code.angularjs.org/1.2.15/angular.js:1382:15
    at Object.invoke (http://code.angularjs.org/1.2.15/angular.js:3805:17)
    at doBootstrap (http://code.angularjs.org/1.2.15/angular.js:1380:14)
    at bootstrap (http://code.angularjs.org/1.2.15/angular.js:1394:12)
    at angularInit (http://code.angularjs.org/1.2.15/angular.js:1307:5)
    at http://code.angularjs.org/1.2.15/angular.js:21163:5
    at HTMLDocument.trigger (http://code.angularjs.org/1.2.15/angular.js:2445:7) angular.js:9563
Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 7; oldVal: 6"],["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldV...<omitted>...5D 
```

I am unsure of what the expected behavior here is, though I would assume a digest error is not it. I would probably expect the same behavior as I would see without the / redirect - stay on the original URL, or even the errored state's URL but not complete the transition.

Is there something I should do differently here to avoid this case, or is this a bug?

Plunker example here: http://plnkr.co/edit/28AQYE?p=preview

**Comment by raulgomis** [comment] 2015-01-16 23:30
Any update on this issue??

**Comment by yousfiSaad** [comment] 2015-01-29 20:48
Any update ..
i try to use it with angular-permission and it goes wrong

**Comment by Avengis** [comment] 2015-02-19 18:44
It worked for me too @KevinOl thanks a lot

**Comment by benoror** [comment] 2015-02-27 16:59
Also fixed by using @dmytro-shchurov and @KevinOl solution:

    $urlRouterProvider.otherwise(function($injector) {
      var $state = $injector.get('$state');
      $state.go('home');
    });

Can anyone explain the cause behind it? Can we expect it to be fixed in a future release?

Cheers!

**Comment by lmk123** [comment] 2015-04-06 13:12
I use v0.2.13 and I didn't fix this issue by using @dmytro-shchurov and @KevinOl solution , it's has another error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: 'rule' must be a function
    at $UrlRouterProvider.otherwise (http://localhost:61111/ys-wms-app/www/vendor/angular/angular-ui-router.js:1814:39)
    at http://localhost:61111/ys-wms-app/www/scripts/app.js:26:36
    at Object.invoke (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:4203:17)
    at runInvokeQueue (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:4109:35)
    at http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:4118:11
    at forEach (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:323:20)
    at loadModules (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:4099:5)
    at createInjector (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:4025:11)
    at doBootstrap (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:1452:20)
    at Object.bootstrap (http://localhost:61111/ys-wms-app/www/vendor/angular/angular.js:1473:12)
http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=app&p1=Error%3A%20…ost%3A61111%2Fys-wms-app%2Fwww%2Fvendor%2Fangular%2Fangular.js%3A1473%3A12)
```

**Comment by raphaelluchini** [comment] 2015-04-06 18:31
I'm getting a similar problem. I have an anchor www.website.com/#something and a route  www.website.com/:slug/:param. When I hit the anchor and then I use url-sref or $state.go, I get Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! after that the router call otherwise and redirect me to '/'

**Comment by morettimatheus** [comment] 2015-05-09 22:45
@dmytro-shchurov solution also worked here. Thank you!

**Comment by kennethlynne** [comment] 2015-07-05 17:30
A "throttle" solved it for me. 
```js
    var redirectInProgress = false;
    $urlRouterProvider.when(/^([\/])?$/, function ($state, $timeout) {
      if (!redirectInProgress) {
        redirectInProgress = true;
        $timeout(function () {
          redirectInProgress = false;
        }, 100);
        return $state.href(App.ui.states.spacesList);
      }
    });
```

**Comment by michaelcunningham19** [comment] 2015-08-15 02:06
@dmytro-shchurov your solution fixed my same issue, using angular-ui-router 0.2.15 w/ angular 1.4.4

**Comment by eddiemonge** [comment] 2015-09-11 22:24
possible duplicate of #2238 ?

https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Closed by eddiemonge** 2015-09-11 22:24 UTC

**Comment by codedbypaul** [comment] 2015-10-22 15:10
I just tried using the following but still get redirected back to the previous state.
```
$urlRouterProvider.otherwise(function($injector) {
  var $state = $injector.get('$state');
  $state.go('home');
});
```

**Comment by elvismdev** [comment] 2015-11-20 02:54
Try placing a `return` before `$state.go()` ?

```
$urlRouterProvider.otherwise(function($injector) {
  var $state = $injector.get('$state');
  return $state.go('home');
});
```

**Comment by nfantone** [comment] 2016-03-21 13:54
@eddiemonge  This is still happening on 0.2.18 using Angular 1.5.2.

[Above solution](https://github.com/angular-ui/ui-router/issues/1022#issuecomment-158264550) fixed it for me. Replacing `.otherwise('some.state')` with:

```js
$urlRouterProvider.otherwise(function($injector) {
  var $state = $injector.get('$state');
  return $state.go('some.state');
});
```

prevents infinite looping.

**Comment by carlosdubus** [comment] 2016-04-03 23:21
I also just experienced this with ionic. $urlRouterProvider.otherwise(function($injector)... Fixed the issue. Just spent 3 hours trying to figure out why the infinite loop.

**Comment by nfantone** [comment] 2016-09-26 22:00
So... It's nearing two years and a half now... 

@eddiemonge Is this still an ongoing issue?

**Comment by mal3ta** [comment] 2017-04-11 14:07
I can confirm that this bug still happens. I solved it with this:

```
$urlRouterProvider.otherwise(function($injector) {
  var $state = $injector.get('$state');
  return $state.go('some.state');
});
```

I am using Angular 1.6.4 and ui-router 0.4.2

**Comment by rameshkumarv** [comment] 2017-05-11 12:13
I'm also faced the same issue, in my case I have **$urlRouterProvider.otherwise("/dashboard")** in route and **event.preventDefault()** in $stateChangeError block. I tried with code mentioned by boonep, that's not solved my case. Problem with my code was I missed /* @ngInject */ in myfile.js. Since I'm using typescript (Don't know exactly, may be build tool require this) I need to use  

> /* @ngInject */ 

Check the error parameter value to identify the exact cause.

> $rootScope.$on("$stateChangeError", (event, toState, toParams, fromState, fromParams, error) => {
> event.preventDefault();
> $state.go("somestate");
> })

**Comment by karanaditya993** [comment] 2017-07-06 17:26
Hello, 

After using the above-mentioned solution for Angular 1.6.4 and ui-router 0.4.2...I'm experiencing the console error of:

Could not resolve '/dashboard' from state ''

Have any of you experienced this?

Thanks
