### ISSUE TITLE
State is loaded again when leaving it after transitionTo+notify=false was used

### ISSUE THREAD

**Issue by agdevbridge** [angular-ui/ui-router#2287] opened 2015-10-05 15:08 UTC
Hello,
i got controller which changes url parameters using transitionTo + notify=false. When leaving it uiRouter loads old state and then new one.
Here is example: http://plnkr.co/edit/8Q8yUKER4ZDYf1grGIDI?p=preview
Using uiRouter develop branch #6f723a599dfab

**Comment by eddiemonge** [comment] 2015-10-06 19:58
Pretty sure this is a duplicate bug. Lets call it a duplicate of #2087 although there are others it could fall under

**Closed by eddiemonge** 2015-10-06 19:58 UTC
Labels: duplicate
