### ISSUE TITLE
'/' get replaced with %252F in url while reloading $state in angular

### ISSUE THREAD

**Issue by Ajeetlakhani** [angular-ui/ui-router#2080] opened 2015-07-05 06:22 UTC
I have url something like this

www.example.com/variable1/variable2

but when i apply

$state.reload(); or 
$state.go($state.current,{},reload:true);

The forward slash get replaced with %252 and url becomes

www.example.com/variable1%252Fvariable2

why it is happening and what can be the solution for this?

**Comment by eddiemonge** [comment] 2015-07-07 19:53
duplicate of #1645 most likely

**Closed by eddiemonge** 2015-07-07 19:53 UTC
Labels: duplicate

**Comment by vejen001** [comment] 2016-07-22 17:40
@Ajeetlakhani I face the same issue, Were you able to figure out the fix for this? BTW which version of ui-router are you using?
