### ISSUE TITLE
$stateParams empty but $state.params is fine

### ISSUE THREAD

**Issue by iq-dot** [angular-ui/ui-router#2076] opened 2015-07-03 17:13 UTC
Hi guys,

I have an issue where the $stateParams is not populated but $state.params is, e.g. my routes:

```
        state('admin.user.create', {
                url: '/create',
                abstract: true,
                templateUrl: 'xyz',
                controller: 'UserCtrl',
                controllerAs: 'createProperty'
            }).

            state('admin.user.create.step1', {
                'url': '/step1',
                templateUrl: 'xyz/step1'
            }).

            state('admin.user.create.step2', {
                'url': '/:userId/step2',
                templateUrl: '/xyz/step2'
            }).
```

Now when I goto 'admin.user.create.step2':
```
console.log($stateParams); // =>  {};
console.log($state.params); // => {userId: 1234}
```

From 'step1' I do this:
```
$state.go('admin.user.create.step2', {userId: user.id});
```

Am I doing anything wrong or misunderstood anything? Or is this a bug?

**Comment by eddiemonge** [comment] 2015-07-07 19:56
@nateabele this really does need better documentation, or to get rid of one of those or make them exactly the same

**Comment by eddiemonge** [comment] 2015-08-26 18:53
calling this a duplicate of https://github.com/angular-ui/ui-router/issues/1984

**Closed by eddiemonge** 2015-08-26 18:53 UTC
Labels: design, pull-to-faq
