### ISSUE TITLE
how to avoid URL encoding 

### ISSUE THREAD

**Issue by saloumfall** [angular-ui/ui-router#3374] opened 2017-03-16 14:29 UTC
sourceUrl:"http://www.techradar.com/news/mobile-computing/laptops/xiaomi-s-first-laptop-is-an-affordable-macbook-air-clone-for-windows-fans-1325480" 

I have a search parameter with this value and each time you press enter a $ state.go is launched and I have  a url encoder which failed my query

ex : sourceUrl:"http://www.techradar.com/news/mobile-computing/laptops/xiaomi-s-first-laptop-is-an-affordable-macbook-air-clone-for-windows-fans-1325480" 
and i got :  sourceUrl:%22http:%2F%2Fwww.techradar.com%2Fnews%2Fmobile-computing%2Flaptops%2Fxiaomi-s-first-laptop-is-an-affordable-macbook-air-clone-for-windows-fans-1325480%22

thx

# Bug Report

#### Current Behavior:

(current behavior here)

#### Expected Behavior:

(expected behavior here)

#### Link to Plunker that reproduces the issue:

http://bit.ly/UIR-Plunk

# Feature Request

(feature request here)

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [ ] I believe my question can only be answered by the UI-Router maintainers

(general query here)

**Comment by christopherthielen** [comment] 2017-03-25 16:46
Closing because you ignored the issue template.

Please either ask on StackOverflow http://bit.ly/UIR-SOF or provide a plunker which reproduces the issue:  http://bit.ly/UIR-Plunk or http://bit.ly/UIR-Plunk1

**Closed by christopherthielen** 2017-03-25 16:46 UTC
