### ISSUE TITLE
Animation - State.go not synchronized with ng-class

### ISSUE THREAD

**Issue by seinavco** [angular-ui/ui-router#1469] opened 2014-10-22 08:36 UTC
Hi,

I want to create animation between state transitions.

I use $state.go() but the transition is not working. I saw that the ng-class is not synchronized between the two ui-view that are changing. Each ui-view has different animation class instead of having the same class to perform the animation in a good way.

It works when I use $location.path().

Thanks

**Comment by m4r71n** [comment] 2015-01-28 11:06
I can confirm this. Demo-Plunk: http://plnkr.co/edit/EaYLo25P4Z7ea2ozIl4B?p=preview

**Comment by m4r71n** [comment] 2015-06-09 21:44
Updated Plunk with Angular 1.3.16 and UI-Router 0.2.15: http://plnkr.co/edit/LTLeOGXwqJUqIygkke8N?p=preview
Updated Plunk with Angular 1.4.0 and UI-Router 0.2.15: http://plnkr.co/edit/MpkvkxNkiZpQQwLNDgGw?p=preview

With Angular 1.4.0 `$location.path()` is also broken

**Comment by eddiemonge** [comment] 2016-03-03 22:31
Closing due to age. If this is still valid in the latest relase, will reopen.

**Closed by eddiemonge** 2016-03-03 22:31 UTC
