### ISSUE TITLE
$transition$ not working when injected in a controller / ui-router 1.0.0-beta.3

### ISSUE THREAD

**Issue by aestheticsdata** [angular-ui/ui-router#3244] opened 2017-01-04 16:44 UTC
in the official doc :

https://ui-router.github.io/docs/latest/modules/ng1.html , in the example : 

```
MyController.$inject = ['$transition$'];
function MyController($transition$) {
  var username = $transition$.params().username;
  // .. do something with username
}
```

$transition$ is injected in the controller, but when I do the same with angular 1.6.1 and ui-router 1.0.0-beta.3 I have the follwing error, using a component architecture:
Error: [$injector:unpr] Unknown provider: $transition$Provider

I am able to inject $transition$ only in a resolve.

**Comment by aestheticsdata** [comment] 2017-01-05 14:03
https://github.com/angular-ui/ui-router/issues/3110

**Comment by christopherthielen** [comment] 2017-01-07 17:33
Closing as duplicate of #3110 

Read this answer which explains why you can't inject `$transition$` or resolves when using route-to-component: https://github.com/angular-ui/ui-router/issues/3110#issuecomment-256204161

**Closed by christopherthielen** 2017-01-07 17:33 UTC

**Comment by christopherthielen** [comment] 2017-01-11 17:56
Now Documented in the route-to-component guide: https://ui-router.github.io/guide/ng1/route-to-component#accessing-transition

**Comment by adamreisnz** [comment] 2017-01-19 18:31
I just ran into this issue as well. I would recommend updating the documentation [here](https://ui-router.github.io/ng1/docs/latest/modules/injectables.html#_transition_) with a link to [here](https://ui-router.github.io/guide/ng1/route-to-component#accessing-transition), because as the OP mentions it states there it can be used to inject into controllers, but doesn't mention it can't be used for routing to components.
