### ISSUE TITLE
Infinite $digest Loop if we do preventDefault() in $stateChangeStart event

### ISSUE THREAD

**Issue by tamtakoe** [angular-ui/ui-router#600] opened 2013-11-25 17:42 UTC
Why $stateChangeStart event fire many times?
http://plnkr.co/edit/QYvRXxciPL9fnyuxiF3l?p=preview

**Comment by stryju** [comment] 2015-01-14 09:55
@frankwallis thanks! this *workaround* seems to fix it (no infinite loop YET :wink:)

**Comment by cgiacomi** [comment] 2015-01-19 11:23
I have the same issue.

Angular 1.3.9
ui-router 0.2.13

I have also tried by adding the following

    $urlRouterProvider.otherwise( function($injector, $location) {
        var $state = $injector.get("$state");
            $state.go("app.home");
    });

but no luck.

I have added the following as well to debug:

    $rootScope.$on('$stateChangeError',function(event, toState, toParams, fromState, fromParams){
      console.log('$stateChangeError - fired when an error occurs during transition.');
      console.log(arguments);
    });

    $rootScope.$on('$stateNotFound',function(event, unfoundState, fromState, fromParams){
      console.log('$stateNotFound '+unfoundState.name +'  - fired when a state cannot be found by its name.');
      console.log(unfoundState, fromState, fromParams);
    });


but they never get called and I still have the infinite loop problem.

It seems to be a problem with present/missing / slashes at the end of the url.

I have downgraded to angular 1.3.0 and the problem goes away, and everything works as it's supposed to.

**Comment by aymericbeaumet** [comment] 2015-01-19 11:27
@cgiacomi I recently updated to Angular `1.3.8` / Angular-ui-router `0.2.13` and I do not face your issue. Can you upgrade to those versions to see if the problem comes from `1.3.9`?

**Comment by cgiacomi** [comment] 2015-01-19 11:48
Hi I have just tested with angular 1.3.8 as well and I still have the problem.

I have though found that the issue is somehow linked to a redirect to /#/ and that seems to fall into the otherwise callback.

I'll try to explain the setup of my routes:

routes.js

    $urlRouterProvider.when('', '/home');

    $urlRouterProvider.otherwise( function($injector, $location) {
        var $state = $injector.get("$state");
        $state.go("notfound"); //redirect to a 404 page
    });

    ... //rest of the routes


config.js

    ... some config code
    $rootScope.$on("$stateChangeStart", function(event, toState, toParams, fromState, fromParams){
      logger.info('stateChangeStart');

      if(!IdentityService.isAuthenticated() && toState.name !== 'login') {
        //user is not logged in and is attempting to go to a different page than the login page.
        $sessionStorage.toState = toState; //save for redirect after successful login
        $sessionStorage.toParams = toParams; //save for redirect after successful login

        logger.info('redirecting to login page.');
        $state.go("login");
        event.preventDefault();
      }



What I have noticed is that if, lets say I navigare to localhost:8000

1) ui router redirects me to /home
2) the check for authenticated user occurs
3) I am ofc redirected to /login
4) the otherwise callback is executed with a the following parameters values for $location:

    $$absUrl: "http://localhost:8000/#/",
    $$path: '/',
    $$url: '/'

and then ofc I end up in the infinite loop. If I remove the otherwise route things work fine. But again with Angular 1.3.0 everything worked fine.

Hope that helps, and thanks for the help :)

**Comment by mark-veenstra** [comment] 2015-04-22 08:13
Solution of @frankwallis works perfectly on 1.3.6

**Comment by vlapo** [comment] 2015-04-23 11:24
Thnx @frankwallis. Works on ancular 1.3.15, ui-router 0.2.13.

**Comment by rainboxx** [comment] 2015-05-08 20:14
We're having this issue, too. We don't have a state for '/' and redirect to a initial state, which will end in an infinite digest loop. Using the function call fixes this issue but is quite an ugly hack.

**Comment by rainboxx** [comment] 2015-05-08 20:56
So what `ui-router` does within `otherwise` is to change the location itself: https://github.com/angular-ui/ui-router/blob/2fff59cbcfd120ed3b5f3d342d03915e751803c2/src/urlRouter.js#L288.  And it seems that changing the state in the aftermath is causing an issue here while, with the function example above, no location change will be triggered initially but a state change.

**Comment by sars** [comment] 2015-05-09 12:23
I tried to debug this issue and got the following:

1. Open url, that has no state configured
2. It is handled by otherwise and change $location to "otherwise" here: https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L2011
3. Angular watches this changes (loop https://github.com/angular/code.angularjs.org/blob/master/1.3.9/angular.js#L14208) 
It handles this changes by https://github.com/angular/code.angularjs.org/blob/master/1.3.9/angular.js#L11398
And sync browser url https://github.com/angular/code.angularjs.org/blob/master/1.3.9/angular.js#L11422
Also it broadcasts $locationChangeSuccess.
4. Ui-router listens $locationChangeSuccess with update function https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L2001
It handles new url by existing state and runs transitionTo() eventually: https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L2347
5. transitionTo broadcast $stateChangeStart https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L3225
6. We listen $stateChangeStart and do preventDefault(). It causes $urlRouter.update() without arguments https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L3227 
and change location back: https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L2072
7. Angular sees than $location not match browser url (browser url now "otherwise"):
https://github.com/angular/code.angularjs.org/blob/master/1.3.9/angular.js#L11405
It changes browser url to not existent and broadcasts $locationChangeSuccess
8. Ui-router handle it and change location again to "otherwise"
9. Angular sees that $location and browser url not match and so on

**Comment by sars** [comment] 2015-05-09 12:29
The problem in logic:
We open not existent url (state)
We change state to otherwise 
BUT we deny this change by preventDefault()

**Comment by welkinwong** [comment] 2015-05-13 02:14
SO EASY. Thanks @frankwallis

**Comment by tomchiverton** [comment] 2015-05-22 10:48
There's something similar wrong with

    $urlRouterProvider.when('/home','/home/global');

because it triggers the same iteration counts and similar work around ( a function as second argument in this case).

**Comment by matteo-mosca** [comment] 2015-05-26 08:49
@frankwallis solution worked for me too, thanks. It is, anyway, a workaround around a released feature that does not work as intended. Hope it will be fixed soon.

**Comment by samueltbrown** [comment] 2015-06-04 17:38
+1 for @frankwallis workaround.  Bailed me out today!

**Comment by axedre** [comment] 2015-06-10 07:07
+1 @frankwallis you made my day! Fixes issue in angular-ui 0.2.13 + angularjs 1.3.13.

**Comment by yf0311** [comment] 2015-06-17 05:22
Thinks @frankwallis.  Fixes issue in angular-ui-router 0.2.13 + angular1.3.15

**Comment by Syldel** [comment] 2015-06-17 15:56
Thank you @frankwallis It works for me too !

**Comment by cameronbourke** [comment] 2015-07-04 11:48
Awesome work @frankwallis. Killing it!

**Comment by agupta1989** [comment] 2015-07-08 12:39
@frankwallis Thanks worked for me too ! Would you please care to explain about the cause of this issue ? I read other comments which might be useful, but I am looking for something more simple explanation :).

**Comment by cameronbourke** [comment] 2015-07-09 08:54
@agupta1989 Some things in life you simply can't explain, and this is one of them haha. Nah it would be cool to know how this gets around the issue!

**Comment by duyn9uyen** [comment] 2015-07-16 19:07
How do I apply the fix mentioned by @frankwallis?

**Comment by afortaleza** [comment] 2015-08-03 13:20
@frankwallis solution works on angular 1.4.3 and ui-router 0.2.15, which was giving me the same behaviour. Thanks a lot, saved my day :+1:

**Comment by eddiemonge** [comment] 2015-08-03 22:16
https://gist.github.com/eddiemonge/f6a58169c2846731a1eb

**Closed by eddiemonge** 2015-08-03 22:16 UTC

**Comment by joshperry** [comment] 2015-08-19 00:23
Has anyone tried this without the workaround on the 1.0 preview code? I don't have time to test it but I am still having this issue on 0.2.x. Going to use the workaround for now.

**Comment by filipesilva** [comment] 2015-08-31 09:57
Using the workaround as well. It works but having to use `$injector` to define the `otherwise` at config time is a nasty break of abstraction.

This issue shouldn't be closed - this is a very real problem for apps that use ui-router to enforce authentication.

**Comment by eddiemonge** [comment] 2015-08-31 18:24
@filipesilva can you open a new issue that describes accurately what exact problem you are having please?

**Comment by GuiToniello** [comment] 2015-09-02 12:38
@frankwallis  +1, thanks :)

**Comment by filipesilva** [comment] 2015-09-06 19:19
@eddiemonge I was having a hard time reproducing it on a plunkr, but finally was able to. Turns out this bug is dependent on the target redirect state having a `templateUrl` instead of inline `template`.

The new issue is #2229.

**Comment by mindontheblink** [comment] 2015-09-14 21:44
@frankwallis thank you!  I spent hours looking into this and just stumbled upon your answer.

**Comment by flipjs** [comment] 2015-09-17 14:39
Is this not fixed yet? I have to use @frankwallis solution to get rid of the warnings. Thank you @frankwallis  for the solution.

**Comment by ogonbat** [comment] 2015-09-25 00:30
Hi All
i have the same error
i have used the solution of @frankwallis but nothing happen
this is my code, this is practically the come coming from ionic with some basic changes

```
angular.module('starter', ['ionic', 'starter.controllers', 'starter.services', 'utils.services', 'user.services', 'ngCordova'])

.run(function($ionicPlatform, $rootScope, $state, SQLiteDB) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleLightContent();
    }
    /*
     create the database
     */
    SQLiteDB.init();

    $rootScope.$on('$stateChangeError',
      function (event, toState, toParams, fromState, fromParams, error) {
        debugger;
    
        console.log('$stateChangeError ' + error && (error.debug || error.message || error));
        // if the error is "noUser" the go to login state
        if (error && error.error === "noUser") {
          event.preventDefault();
          $state.go('user-login', {});
        }
      });
  });
})

.config(function($stateProvider, $urlRouterProvider) {

  // Ionic uses AngularUI Router which uses the concept of states
  // Learn more here: https://github.com/angular-ui/ui-router
  // Set up the various states which the app can be in.
  // Each state's controller can be found in controllers.js
  $stateProvider

  // setup an abstract state for the tabs directive
    .state('tab', {
    url: '/tab',
    abstract: true,
    templateUrl: 'templates/tabs.html',
      resolve: {
        user: function (UserService) {
          var value = UserService.init();
          return value;
        }
      }
  })

  // Each tab has its own nav history stack:

  .state('tab.dash', {
    url: '/dash',
    views: {
      'tab-dash': {
        templateUrl: 'templates/tab-dash.html',
        controller: 'DashCtrl'
      }
    }
  })

  .state('tab.chats', {
      url: '/chats',
      views: {
        'tab-chats': {
          templateUrl: 'templates/tab-chats.html',
          controller: 'ChatsCtrl'
        }
      }
    })
    .state('tab.chat-detail', {
      url: '/chats/:chatId',
      views: {
        'tab-chats': {
          templateUrl: 'templates/chat-detail.html',
          controller: 'ChatDetailCtrl'
        }
      }
    })

  .state('tab.account', {
    url: '/account',
    views: {
      'tab-account': {
        templateUrl: 'templates/tab-account.html',
        controller: 'AccountCtrl'
      }
    }

  })
      .state('track', {
                url: "/track",
                templateUrl: "templates/track.html",
                controller: "TrackCtrl"
                })
      .state('user-login', {
                url: "/login",
                templateUrl: "templates/login.html",
                controller: "LoginCtrl"
                });

  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/tab/dash');

});
````
and this is the error

```
[Error] Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:8895:32
$digest@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:24548:35
$apply@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:24778:31
file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:58933:24
eventHandler@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:12098:25
dispatchEvent@[native code]
triggerMouseEvent@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:2865:20
tapClick@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:2854:20
tapTouchEnd@file:///Users/ogonbat/Library/Developer/CoreSimulator/Devices/63B46F72-A09A-4C30-BFD1-932A0D5A662B/data/Containers/Bundle/Application/50BFCEFC-269A-4C69-B944-F215DBD5EDB7/myRoutes.app/www/lib/ionic/js/ionic.bundle.js:2977:13
	(función anónima)
	(función anónima)
	$apply
	(función anónima)
	eventHandler
	dispatchEvent
	triggerMouseEvent
	tapClick
	tapTouchEnd
[Error] Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.4.3/$rootScope/infdig?p0=10&p1=%5B%5D
	$apply
	(función anónima)
	eventHandler
	dispatchEvent
	triggerMouseEvent
	tapClick
	tapTouchEnd
```

**Comment by axedre** [comment] 2015-09-25 07:23
@ogonbat doesn't seem you applied @frankwallis 's solution, he suggests writing:
```
$urlRouterProvider.otherwise( function($injector, $location) {
    var $state = $injector.get("$state");
    $state.go("app.home");
});
```
but seems you wrote:
```
$urlRouterProvider.otherwise('/tab/dash');
```

**Comment by ogonbat** [comment] 2015-09-25 20:17
Hi @axedre , thank you for your reply
i have tested the @frankwallis method but, when i run the emulator ( iphone ) the $state redirect to tab and not to tab.dash
all work well if i redirect to track page, for example, so if i redirect to a nested route something goes wrong.
have any idea?

**Comment by filipesilva** [comment] 2015-09-25 20:22
Wait, iphone? I remember that there is an issue with ionic and iOS 9
http://blog.ionic.io/ios-9-potential-breaking-change/

```
We’ve tested a number of widely-used Ionic apps with iOS 9 beta and GM, and issues appear to be isolated to intermittent UI/navigation issues on some apps, along with console errors indicating infinite digest warnings in Angular. Functionality beyond that should not be impacted.
```

**Comment by ogonbat** [comment] 2015-09-25 20:33
hi @filipesilva 
this is true, this is a bug with ios9, is not directly related with this bug.
thanks you for your help and sorry

**Comment by filipesilva** [comment] 2015-09-25 22:18
Glad to have been of help to a fellow ionic dev :D

**Comment by elbidone** [comment] 2015-09-29 16:53
I had the same issue and fix it upgrading to angular 1.4.6, as recommended on 
>  The patch can be applied to Angular 1.2.0 – 1.4.5. Newer versions of Angularhave the workaround baked in.

**Comment by marthinus-engelbrecht** [comment] 2015-10-27 23:25
I can confirm that I'm still facing this is issue even with upgrade to angular 1.4.6. It's also still an issue on 1.4.7.

**Comment by ewhitmore** [comment] 2015-10-29 19:51
@filipesilva @ogonbat having the same issue with my ionic app.  I thought it was the ios 9 bug but happened upon this thread which is my actual problem.  Still haven't been able to implement the workaround successfully yet.

**Comment by filipesilva** [comment] 2015-10-30 11:01
@ewhitmore I'm doing what @frankwallis mentioned https://github.com/angular-ui/ui-router/issues/600#issuecomment-47228922, and it's been working well so far.

**Comment by ewhitmore** [comment] 2015-10-30 12:54
@filipesilva I was able to get it working as well with @frankwallis workaround.

**Comment by filipesilva** [comment] 2015-10-30 13:48
Glad to have helped!

**Comment by chandramuralis** [comment] 2015-11-05 20:50
@marthinus-engelbrecht I'm also getting same issue even on 1.4.5, fortunately @frankwallis solution worked for me.

**Comment by niyando** [comment] 2015-11-23 10:41
@frankwallis :beers:

**Comment by btamayo** [comment] 2015-11-23 22:47
@frankwallis :+1: Thank you!

**Comment by umbacclifford** [comment] 2015-11-26 04:45
@frankwallis .Thank you!

**Comment by hnguyenec** [comment] 2015-11-27 01:39
@frankwallis +1

**Comment by dellheng** [comment] 2015-12-01 08:51
@frankwallis +1

**Comment by sh-guti** [comment] 2015-12-01 15:35
@frankwallis  Thank you!!

**Comment by Elmanderrr** [comment] 2015-12-28 07:01
@frankwallis +1

**Comment by pjwalmsley** [comment] 2016-01-07 22:08
+1

**Comment by tania-pets** [comment] 2016-01-22 12:28
@frankwallis +1

**Comment by venkateshappala** [comment] 2016-01-22 20:11
I am also facing infinite loop issue. I have plain html with Login and Logout button. On clicking login, getting Angular infinite digest issue. Can anyone help how to apply workaround in my solution? Please find below code. 

HTML:
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>My Page</title>
</head>
<body ng-app="PowerBISPO" ng-controller="powerBICtrl">
    <div class="row">
        <p class="app-error"></p>
        <input type="button" class="app-login" ng-hide="userInfo.isAuthenticated" ng-click="login()" value="Login" />
        <input type="button" class="app-login" ng-show="userInfo.isAuthenticated" ng-click="logout()" value="Logout" />
    </div>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="https://code.angularjs.org/1.2.25/angular-route.js"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/adal.min.js"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/adal-angular.min.js"></script>
    <script src="home.js"></script>
</body>
</html>

JS:

'use strict';
angular.module('PowerBISPO', ['ngRoute', 'AdalAngular'])
.config(['$routeProvider', '$httpProvider', 'adalAuthenticationServiceProvider', function ($routeProvider, $httpProvider, adalProvider) {

    adalProvider.init(
        {
            instance: 'https://login.microsoftonline.com/',
            tenant: 'microsoft.onmicrosoft.com',
            clientId: 'xxxxx-xxxx-xxxx-xxx-xxx',
            extraQueryParameter: 'nux=1',
            cacheLocation: 'localStorage' // enable this for IE, as sessionStorage does not work for localhost.
        },
            $httpProvider
        );

}])

.controller('powerBICtrl', ['$scope', 'adalAuthenticationService', '$location', function ($scope, adalService, $location) {
    $scope.login = function () {
        adalService.login();
    };
    $scope.logout = function () {
        adalService.logOut();
    };
}]);

**Comment by venkateshappala** [comment] 2016-01-22 20:13
I have HTML with Login and Logout buttons. On successful login, I am also facing infinite loop issue. Please find attached code. Simple code. Can anyone help me on applying workaround for this issue?
Thanks in advance!!
[Adal-Angular.zip](https://github.com/angular-ui/ui-router/files/101371/Adal-Angular.zip)

**Comment by blunatic** [comment] 2016-01-22 23:28
Amazing that this still isn't fixed.

@frankwallis another +1 to you.

**Comment by nateabele** [comment] 2016-01-23 02:15
@blunatic Well, it's a large, widely-used project, so we have a lot to focus on. This isn't high on our priority list because, at first glance, the fix is non-trivial, and what's more, there's a simple, unobtrusive workaround.

If it's so 'amazing' to you that we have yet to take time out of our busy schedules to fix it anyway, maybe you could take some time out of yours and start [here](https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md#contribute). :smile:

**Comment by blunatic** [comment] 2016-01-23 02:19
@nateabele understandable. Didn't mean to come across as a jerk. My apologies.

**Comment by agupta1989** [comment] 2016-01-23 02:20
@nateabele :+1:

**Comment by nateabele** [comment] 2016-01-23 02:20
Not at all. Just explaining the rationale.

**Comment by christopherthielen** [comment] 2016-01-23 23:22
I came to the same conclusion as @sars comment.  See #2238 
Fix should be forthcoming in 0.2.16

**Comment by pjwalmsley** [comment] 2016-01-26 21:36
@venkateshappala 

Hope you figured things out.  I really don't think that's enough context, I'd presume the issue lies somewhere in the adal.login method.

**Comment by jbennie** [comment] 2016-01-26 22:24
// the following code will allow you to default to the login , unless your are logged in then it will default to the preferred page. 

Make sure that the

$stateProvider.state .... ;   //this must be first otherwise the state object you want to go to wont exist.  

$urlRouterProvider.otherwise(function ($injector, $location) {
            var $state = $injector.get("$state");
            var authService = $injector.get("authService");

            if (authService.authentication.isAuth) {
                $state.go("library.search");
            } else {
                $state.go("home.login");
            }
        });

// then in run

 $rootScope.$on("$stateChangeStart", function (event, toState, toParams, fromState, fromParams) {
            //  if ($rootScope.appAuth.authentication.isAuth == false && $rootScope.appAuth.authentication.profile !== 'undefined') 

            if (authService) {
                if (!authService.IsAnnonPage(toState.name)) {
                    if (!authService.authentication.isAuth && toState.name != 'home.login') {
                        event.preventDefault();

                        $state.go('home.login');
                        return;
                    }
                }
            }
            else {
                $state.go('home.login');
            }

        });

**Comment by ggarg2** [comment] 2016-02-01 21:32
@frankwallis +1

**Comment by masoodtrb** [comment] 2016-02-06 21:38
@frankwallis Thank you

**Comment by sandor11** [comment] 2016-03-07 11:08
@frankwallis Thanks! You have just ended 2 hours of pain.

**Comment by nfantone** [comment] 2016-03-21 18:08
This is still an on going issue. @frankwallis workaround is still the way to go.

https://github.com/angular-ui/ui-router/issues/1022#issuecomment-199292756

Wasn't fixed on 0.2.16 as @christopherthielen mentioned. 

This shouldn't be closed. (cc. @nateabele)

**Comment by nigel-dewar** [comment] 2016-04-01 23:54
Wow is this issue really not fixed yet??

**Comment by nfantone** [comment] 2016-04-02 01:26
Noup, it's not.

**Comment by nigel-dewar** [comment] 2016-04-03 21:43
@nfantone , thanks for letting me know. cheers.

**Comment by andreiho** [comment] 2016-08-04 07:52
Almost 3 years later, still experiencing the same issue. Thankfully @frankwallis workaround does the trick.

For anybody coming across this issue, here's the workaround (so you don't have to look for it in this long thread):

> I also had this issue, you can fix it by using the other version of otherwise which takes a function:

> ```
$urlRouterProvider.otherwise(function($injector) {
  var $state = $injector.get('$state');
  $state.go('app.home');
});
```
