### ISSUE TITLE
State reloaded on exit after change URL with notify:false, reload:false

### ISSUE THREAD

**Issue by alexcrown** [angular-ui/ui-router#2139] opened 2015-07-29 16:06 UTC
Problem: I use recepie from #64 for change URL without state change ({notify:false, reload:false}. When I realy change state to another, previous state with changed url reload it`s controller. 

Steps to reproduce:
1. Open [Plunker](http://plnkr.co/edit/v1cORNMvBct8wk6oAqLl)
2. Click Route1. url = #/route1/1 , console output = route1
3. Click "Change URL with test=hello". url=#/route1/1?test=hello 
4. Click "Change url with test=world". url=#/route1/1?test=world
5. Click Route 2. url = #/route2/2, **console output = route1 and route2.**

Why route1 reload it's controller on step 5 and how prevent it?

**Comment by eddiemonge** [comment] 2015-07-29 18:09
duplicate of https://github.com/angular-ui/ui-router/issues/1673

**Closed by eddiemonge** 2015-07-29 18:09 UTC

**Comment by btm1** [comment] 2015-07-29 21:10
@eddiemonge it is a dup of https://github.com/angular-ui/ui-router/issues/1673 but why is that issue closed it's not fixed yet... even if you hack $state.go to achieve changing the params it messed up once you try to nav to a new state... it will reload the same controller

**Comment by eddiemonge** [comment] 2015-07-29 21:31
Its not closed
