### ISSUE TITLE
version 0.3.2 ui-sref-active="active" ERROR

### ISSUE THREAD

**Issue by iMolodecGit** [angular-ui/ui-router#3133] opened 2016-11-06 20:16 UTC
`<li class="online-users" ui-sref-active="active">
            <a href ui-sref="users-online">online users</a>
        </li>`
this code don't work on new version. reason -  ui-sref-active="active"

**Comment by christopherthielen** [comment] 2016-11-08 01:18
This bug report doesn't explain what the problem is.

Put this code into a punker and show me how to re-create the error.  I provided a Plunker link that shows that the code does seem to work.  

http://plnkr.co/edit/nF3Rve2gX5GGjWTSMXQt?p=preview

I'm going to close this for now, because it seems like the code does work.  If you can link to a plunker that demonstrates the problem, I'll gladly reopen this.

**Closed by christopherthielen** 2016-11-08 01:18 UTC
Labels: not enough information, PlunkrPlease

**Comment by chesminsky** [comment] 2016-11-10 15:19
im facing the same problem

**Comment by christopherthielen** [comment] 2016-11-10 15:20
Ok, then post a reproduction

**Comment by iMolodecGit** [comment] 2016-11-10 16:04
@chesminsky my problem was in using gulp.min.js
