### ISSUE TITLE
Redirects to child states don't trigger parent's resolves 

### ISSUE THREAD

**Issue by archasek** [angular-ui/ui-router#3142] opened 2016-11-09 14:19 UTC
Hi!

Ui-router v v1.0.0-beta.3
AngularJS 1.5.8

I have something like this:

```
    $urlRouterProvider
        .otherwise('/test');

    $stateProvider
        .state('index', {
            abstract: true,
            resolve: {
                resolving: function () {
                    console.log('resolving fired')
                }
            }
        })
        .state('index.test', {
            url: '/test',
        });
```
I go to `/otherwiseee` and unfortunately resolve isn't fired in the parent. If I put resolve into the child state, it's fired.
I would like to have some kind of auth resolve for all children states.
Am I doing it wrong? :)

I think the resolve is fired only when I try to refresh the page or get into the child state by typing the url in the browser for the first time (when the app isn't loaded yet).
When I use `$state.go()` or write the url in the address bar (when the app is already loaded), the parent resolve isn't fired.

**Comment by christopherthielen** [comment] 2016-11-09 20:15
The behavior you describe it does not sound correct.  Can you reproduce this for me?

I'm fairly certain the resolve is getting involved anytime the `index` state is entered.  That should include all of the above mechanisms: Typing the URL in the browser for the first time, refreshing the page, using state.go (from any state that is not a child of `index`)

**Comment by archasek** [comment] 2016-11-10 12:17
@christopherthielen could you please check it out? http://plnkr.co/edit/s0wYWVUMkQ5K6I3KRP5O?p=preview

**Comment by christopherthielen** [comment] 2016-11-10 16:28
This is a misunderstanding.  

Resolves trigger when a state is *entered*.  Your resolve is defined on the `index` parent state.  The initial state is `index.home`.  When you click the link, it transitions from `index.home` to `index.admin.home`.  *Since `index` is already entered, the resolve does not get rerun.*  

This is so you can load data once (in a parent state) and navigate between children without continually fetching the parent data.  When a transition between children occurs, we say that the parent states are "retained".

---

Resolve should be used to load async application data, such as fetching a user by an id parameter.  For things like authentication, you should use a Transition Hook.

http://plnkr.co/edit/Jj9xhyXoyuyHyCDlxHzO?p=preview

Closing since this works as designed.
I suggest playing with the transition visualizer to get a better understanding of exiting and entering states.

**Closed by christopherthielen** 2016-11-10 16:28 UTC

**Comment by archasek** [comment] 2016-11-10 16:40
Thank you, I will play with Transition Hook.
