### ISSUE TITLE
0.2.17 - $scope '$destroy' of old route now fired after new route controller created

### ISSUE THREAD

**Issue by jamesbrobb** [angular-ui/ui-router#2518] opened 2016-02-03 17:52 UTC
I've just updated to 0.2.17 (from 0.2.15) and it appears to have introduced a bug.

When i navigate to a new route, it's controllers are now created _before_ the `'$destroy'` event of the `$scope` of the route controller that's being exited is fired.

[0.2.17 example](http://codepen.io/anon/pen/NxLreB)

And this is the previous behaviour

[0.2.15 example](http://codepen.io/anon/pen/adaZgd)

**Comment by nateabele** [comment] 2016-02-03 17:58
This is a duplicate of #2485. Please see the discussion there. Thanks.

**Closed by nateabele** 2016-02-03 17:58 UTC
