### ISSUE TITLE
underscore in component name makes route to not run

### ISSUE THREAD

**Issue by akarelas** [angular-ui/ui-router#3211] opened 2016-12-18 17:21 UTC
This doesn't work on Angular 1.6:

```javascript
angular.module('myApp').component('app_a', {
    template: '123',
    controller: class AppCtrl {
        constructor() {
            console.log(234);
        }
    }
});

angular.module('myApp').config(function($stateProvider) {
    $stateProvider.state({
        name: 'app',
        url: '/',
        component: 'app_a'
    });
});
```

It does not display anything on the browser or the console log. If I remove the underscore on the component name, however, I get output both on the browser and the console. Isn't this a bug?

**Comment by christopherthielen** [comment] 2016-12-19 17:24
I don't think component names should have underscores in them.

According to the ng docs, [names are normalized to camel case](https://docs.angularjs.org/guide/directive#normalization).  Your component should be named `appA`.  When html such as `<app_a></app_a>` is parsed, it looks up the `appA` directive.

Here's a plunker that shows how this works in ng1.6: http://plnkr.co/edit/WviuDDgu66OmHk6NZryn?p=preview

**Comment by christopherthielen** [comment] 2016-12-19 17:25
Closing, because I think this is not a bug.

**Closed by christopherthielen** 2016-12-19 17:25 UTC
