### ISSUE TITLE
parent resolve overiding child resolve in child state - with same controller in child and parent

### ISSUE THREAD

**Issue by fyyyyy** [angular-ui/ui-router#2529] opened 2016-02-05 11:00 UTC
Still having the same issue with 0.2.15, when children use same controller as parent #1534 

Actually, it tries to resolve because console.log('resolve overwrite'); is fired after console.log('resolve first');
However the injected value is not overwritten.

```javascript

stateProvider

            .state('polygons', {
                url: '/',
                templateUrl: 'app/main/main.html',
                controller: 'MainController',
                resolve: {
                    polygon: function () {
                        console.log('resolve first');
                        return false
                    },
                    cities: [
                        ...
                        }
                    ]
                }
            })


            .state('polygons.new', {
                url: 'polygon/new',
                templateUrl: 'app/main/details/details.html',
                resolve: {
                    polygon: [
                        'polygonService',
                        function (polygonService) {
                            console.log('resolve overwrite');
                            var res = polygonService.new()
                            return res;
                        }
                    ]
                },
                onEnter: function (polygon) {
                   ...
                },
                onExit: function (polygon) {
                    ...
                }
            })


            .state('polygons.details', {
                url: 'polygon/:id',
                templateUrl: 'app/main/details/details.html',
                resolve: {
                    polygon: [
                        'polygonService',
                        '$stateParams',
                        function (polygonService, $stateParams) {

                            if (polygonService.getOne($stateParams.id)) {
                                return polygonService.getOne($stateParams.id);
                            } else {
                                return polygonService.setOne($stateParams.id).then(
                                    function () {
                                        return polygonService.getOne($stateParams.id);
                                    });
                            }

                        }
                    ]
                },
                onEnter: function (polygon) {
                    ...
                },
                onExit: function (polygon) {
                  ...
                }
            })

**Comment by christopherthielen** [comment] 2016-02-05 16:05
This is by design.  Resolve data is scoped to the state the resolve is in and all substates.  Child resolves can override the parent resolve (by re-using the name), but it only affects the child state and substates.  The child resolve is a different object that occludes the parent resolve.  This is similar to $scope inheritance works, where a child scope can re-assign a scope variable; the value is accessible by the children but not by the parent.

Your code has a single controller instance defined in the parent.  When the controller is **instantiated (within the context of the parent state)**, the parent resolve is injected.  The child states have no controllers, and nothing ever injects the child resolves.

Note that  #1534 works against release 0.2.17

Hope this helps.   Closing, because this works as designed.

**Closed by christopherthielen** 2016-02-05 16:05 UTC

**Comment by fyyyyy** [comment] 2016-02-05 17:39
Thanks

Imo, this isnt what the documentation says, it just says children can overwrite the resolve, i think it should note this only works with different controllers.

This sort of destroys the usefulness of using resolve with sub-views to have different data available while still sharing the same controller. Especially since it would work for full-page refreshes vs other solutions that need custom handling like passing the sub-view data via scope.

**Comment by christopherthielen** [comment] 2016-02-06 17:06
> sub-views to have different data available while still sharing the same controller

That doesn't quite seem like the right approach to me, although you're close.

I see you're using the resolve override to implement two substates, `new` and `edit`.  That seems like a good approach.  However, I'd move the *controller* for editing the polygon down to those two child states, and inject the data from the appropriate resolve.

I just did something similar in the new sample app: 
[the 'edit' state wraps the existing parent resolve](https://github.com/ui-router/sample-app/blob/master/app/contacts/editContact.state.js#L16-L20)
[the 'new' state creates a blank model](https://github.com/ui-router/sample-app/blob/master/app/contacts/newContact.state.js#L13-L16)

[The shared controller gets a model (new or existing) injected](https://github.com/ui-router/sample-app/blob/master/app/contacts/editContact.component.js#L31)

**Comment by fyyyyy** [comment] 2016-02-09 10:33
Thanks @christopherthielen 
Our app uses a list that is always visible in / and child states. If you click on a list item, the list is still visible and the item details are shown on a sidebar. This why i always wanted to share the controller. But now with your example i realized all it needed was a sub controller that extends main controller. I had almost given up, thanks :D Here's a :cookie: for you!

```js

  function SubController(
      $scope,
      $controller,
      polygon
  ){

      angular.extend(this, $controller('MainController', {$scope: $scope}));

      angular.extend($scope, {
          polygon: polygon
      });

  }
})();
