### ISSUE TITLE
Nested lazy loaded state cannot be accessed via url

### ISSUE THREAD

**Issue by lencyforce** [angular-ui/ui-router#3146] opened 2016-11-11 08:01 UTC
I have a lazy loaded parent state:

```js
{
    name: 'home',
    url: '/home',
    lazyLoad: ...
}
```
which will return another lazy loaded child state in the lazyLoad promise:
```js
{
    name: 'home.publish',
    url: '/publish',
    lazyLoad: ...
}
```

Now that I can successfully navigate to "/home/publish/edit" using $state.go('home.publish.edit') before the parent state lazy loading taking place, however, directly accessing "/home/publish/edit" in the browser gives me the error "No such state 'home.publish'" after both the parent and child's lazy loading finished.

**Comment by christopherthielen** [comment] 2016-11-11 16:21
I believe this is a duplicate of https://github.com/ui-router/react/issues/7 and is fixed by https://github.com/ui-router/core/commit/1c6220c3938818b0a97796713d1b033231458318

I hope to have a new release for ng1 next week.

**Comment by christopherthielen** [comment] 2016-11-11 16:22
Closing as this has already been fixed in `ui-router-core/master`

**Closed by christopherthielen** 2016-11-11 16:22 UTC
Labels: 1.0, bug
