### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by ionescuvictor** [angular-ui/ui-router#2236] opened 2015-09-10 16:07 UTC
I have this code.Here is the plnkr . http://plnkr.co/edit/FtWBfKaZ9VsCN1tT6nef?p=preview

on the 

App.run(function ($rootScope, currentUser, $state, $location) {

    $rootScope.$on('$stateChangeStart',
           function (event, toState, toParams, fromState, fromParams) {
               
               if (localStorage.getItem("Token") == null && toState.name != "loginPage") {
                   event.preventDefault();
                   $state.go('loginPage', { redirectUrl: toState.name });
                   return;
               }

           });
});

The problem is that it goes around and around in a loop, until i get max 10 digest error.My javascript knowledge is rather limited.Can somebody please help me?

**Comment by ionescuvictor** [comment] 2015-09-10 16:12
well i found the answer.I had to do this, perhaps somebody explain what is going on? and maybhe fix this bug?

  $urlRouterProvider.otherwise(function ($injector, $location) { // nasty bug.
        var $state = $injector.get("$state");
        $state.go("home");
    });

**Comment by eddiemonge** [comment] 2015-09-11 19:00
Can you post a plnkr example please?

**Comment by ionescuvictor** [comment] 2015-09-11 20:35
http://plnkr.co/edit/FtWBfKaZ9VsCN1tT6nef?p=preview

 here you go.

Open up the console and you can clearly see 10 digest cycles reached.

**Comment by eddiemonge** [comment] 2015-09-11 21:49
Duplicate of #2238

**Closed by eddiemonge** 2015-09-11 21:49 UTC
Labels: PlunkrPlease
