### ISSUE TITLE
$state.go don't work in resolve

### ISSUE THREAD

**Issue by BjornMelgaard** [angular-ui/ui-router#2789] opened 2016-06-03 18:48 UTC
```coffee
.state 'users.show',
  url: '/:id'
  controller: "UserController"
  templateUrl: 'users/show.html'
  resolve:
    user: ["$state", "$location", "$stateParams", "UserResource", ($state, $location, $
stateParams, UserResource) ->
      $state.go("users.list") unless $stateParams.id # *this line*
      return UserResource.get( { id: $stateParams.id } )
    ]
    isOwner: ["$auth", "$stateParams", "$q", ($auth, $stateParams, $q) ->
      $auth.validateUser().then ->
        return `$auth.user.id == $stateParams.id`
    ]
```
Also don't work `$location.go("/users")`, but work `$state.go("users.list") unless $stateParams.id` defined in `onEnter` event (but `UserResource.get( { id: $stateParams.id } )` still process against logic)

[Application](https://github.com/BjornMelgaard/poller/blob/master/app/assets/javascripts/routes.coffee)

P.S. this work well

 ```coffee
   .state 'my_profile',
      resolve:
        auth: ["$auth", "$state", ($auth, $state) ->
          $auth.validateUser().then ->
            $state.go("users.show", {id: $auth.user.id})
        ]
```

**Comment by christopherthielen** [comment] 2016-06-03 19:42
Confirmed this is a longstanding bug.  However, we're not going to fix it in the `legacy` branch because it's already been fixed in the `master` branch, which is the 1.0.0 alpha.

You can probably work around the problem by 1) rejecting the resolve and 2) adding a timeout
```
if !$stateParams.id
    $timeout () -> $state.go("users.list")
    return $q.reject()
```

**Closed by christopherthielen** 2016-06-03 19:42 UTC
