### ISSUE TITLE
Slashes are double encoded in hash query params

### ISSUE THREAD

**Issue by natefaubion** [angular-ui/ui-router#1973] opened 2015-05-20 20:25 UTC
I have a link that's something like
```html
<a ui-sref="myState({ path: '/foo' })">Go</a>
```

Which results in the hash-url `#/my-state?path=%252Ffoo`. The slash being encoded to `%2F` and the percent being encoded to `%25`. In `0.2.13` this double-encoding seemed to work fine, as the new state picks it up correctly (as `/foo`), but in `0.2.14` and `0.2.15` the new state will only get it decoded once, resulting in `%2Ffoo`.

**Comment by natefaubion** [comment] 2015-05-20 21:18
I've actually found that ui-router is transitioning twice on this link. If I don't have a slash in the query param, it transitions once. But once I add the slash it does two transitions, one immediately after the other. The first transition get the correct param, and the second is double encoded.

**Comment by natefaubion** [comment] 2015-05-21 14:37
I've also found that if you provide a direct url like `#/my-state?path=/foo` (not through a ui-sref link), the router automatically navigates to `#/my-state?path=%2Ffoo` (not double-encoded) which works, but inserts a new history item, which breaks the back button (when you hit back it just keeps redirecting you over and over again).

**Comment by ckniffen** [comment] 2015-05-27 21:59
This is related to #1645.  Before 0.2.14 the issue was more cosmetic but with the addition of the `$normalize` method on types the decode function will no longer be called for params of type `string`.

I have created a failing test for it.
```
it("should encode and decode slashes in parameter values", function () {
    var matcher = new UrlMatcher('/:foo');
    expect(matcher.format({ foo: "/" })).toBe('/%252F');
    expect(matcher.format({ foo: "//" })).toBe('/%252F%252F');
    expect(matcher.exec('/%2F').foo).toBe('/');
    expect(matcher.exec('/%2F%2F').foo).toBe('//');
 });
```
Previously the test did have assertions for decoding.

## Solution 1
Have the `string` type override `$normalize` to always call decode

```
string: {
      encode: valToString,
      decode: valFromString,
      $normalize: function(val){ return this.decode(val); },
      is: function(val) { return val == null || !isDefined(val) || typeof val === "string"; },
      pattern: /[^/]*/
}
```

## Solution 2

Update is method to `is` method to check for `\` encoding.

**Comment by piupiupiu** [comment] 2015-06-16 17:34
Unfortunately, it seems it is not fixed.

My configuration is the following:
```
$stateProvider
        .state('root',{
            url: '/{lang:(?:[A-Za-z]{2}/)?}',
            abstract: true,
            template: '<ui-view />',
        })
        .state('root.index', {
            url: '',
            template: 'Index Controller',
            controller: function() {
                console.log('Index Controller');
            }  
        })
       .state('root.page', {
            url: '{url:[A-Za-z0-9]+}',
            resolve: {
                url: ['$stateParams', function($stateParams) {
                         return $stateParams.url;
                     }]
            },           
            controller: ['$state', 'url', function($state, url) {
                              if (url === 'abc') {
                                  $state.go('root.page.blog');
                              } else {
                                  $state.go('root.page.category');
                             }
                        }]
        })
        .state('root.page.blog', {
            url: '',
            controller: function() {
                console.log("Blog Controller");
            },
            template: 'Blog Controller'
        })
        .state('root.page.category', {
            url: '',
            controller: function() {
                console.log("Category Controller");
            },
            template: 'Category Controller'
        })
```

In brief, I need to handle root url `/` and language subdirectories root by Index Controller,
and rest urls by Category or Blog controller.

It works fine in all cases but if I try to access any urls under language subdirectory.
E.g. 

http://example.com/es/abc

it shows the correct view but redirects to a wrong url:

http://example.com/es%252Fabc

However, this works fine:

http://example.com/abc

Please advise.

**Comment by piupiupiu** [comment] 2015-06-21 12:44
Unfortunately, it seems it's not fixed.

My configuration

    $stateProvider
        .state('root',{
            url: '/{lang:(?:[A-Za-z]{2}/)?}',
            abstract: true,
            template: '<ui-view />',
        })
        .state('root.index', {
            url: '',
            template: 'Index Controller',
            controller: function() {
                console.log('Index Controller');
            }  
        });
  

It should match: `http://example.com/` and `http://example.com/es/`.

However, the optional back slash is encoded when you go to `$state.go('root.index',{lang:'es'})`;

and url becomes: 

http://example.com/es%252F

After some investigation I found the script is not decoded because the back slash is double encoded:

First of all,  there is the following code:

    var encoded = param.type.encode(value);

This code launches the re-defined `encode` function which replaces the slashes with their encoded entities. So `es/` becomes `es%2F`.

Then the string is double encoded here: `result += encodeURIComponent(encoded);`

Therefore it becomes `es%252F`.

 I managed to fix it this way: 

    function valToString(val) { return val != null ? val.toString().replace(/\//g, "%2F") : val; }

replaced with

    function valToString(val) { return val != null ? encodeURIComponent(val.toString()) : val; }

and 

    result += encodeURIComponent(encoded);

replaced with

    result += encoded;

I'm not quite familiar with ui-router so I don't know if this solution is correct but at fixes my case.

**Comment by piupiupiu** [comment] 2015-06-28 16:37
Update:

Unfortunately, my fix is incomplete.
It does not work in case of `ui-sref` directive.

`<a ui-sref="root.index({lang: 'es/'})">test</a>` becomes `<a href="es%2F">test</a>`

Could anybody take a look at the issue?

**Comment by eddiemonge** [comment] 2015-06-29 19:09
I am going to close this as a duplicate of #1645 and if fixing that doesn't fix this then I'll reopen it.

**Closed by eddiemonge** 2015-06-29 19:09 UTC

**Comment by tomasdev** [comment] 2016-01-30 04:34
Could we please re-open this ticket?

`$state.go('fetch', { api: 'http://api.myserver.com' });` goes to `#/fetch?api=http:%252F%252Fapi.myserver.com` ...
