### ISSUE TITLE
Dynamic params and query params, url not updated?

### ISSUE THREAD

**Issue by Ben305** [angular-ui/ui-router#2709] opened 2016-04-24 12:05 UTC
Hi there, I'm using version `1.0.0-alpha.4` because I have the following use case:

I have to implement a search, and the parameters are passed via query params like this: `/search?city=Boston&start=2016-01-01&end=2016-01-10`

The state is defined like this:
```javascript
$stateProvider.state('search', {
    url: '/search?city&startDate&endDate',
    templateUrl: 'some/url/template.html',	
    params: {
        city: {
             value: 'Boston'
	     dynamic: true
	},
	startDate: {
	     value: '2016-01-01',
		dynamic: true
	},
	endDate: {
	    value: '2016-01-10',
		dynamic: true
	}
}
```

Everything is working well, and when the user updates the parameters, I'm calling `$state.go($state.current.name, newStateParams);`, and the callback function `uiOnParamsChanged` is also called correctly.

Only the parameters in the url are not updated. So when the user wants to search in Chicago, the url is still `search?city=Boston...` after the state-change. Is this the correct behavior? Do I have to update the url manually?

**Comment by christopherthielen** [comment] 2016-04-25 03:14
No you shouldn't  need to manually update the URL. This sounds like a bug.

**Comment by dracula92107** [comment] 2016-04-28 11:16
Hi,
I have a similar issue.
My define:
```
$stateProvider.state('zone', {
    url: '/zone-:zoneId',
    templateUrl: '/zone-detail.html',
    controller: 'zoneController'
});
```

When I click on link on view (use ui-sref) or use `$state.go`, it redirect success. But when I change the zoneId on address bar -> state not change.
The back button not work, too.

Test on Chrome.

Is this a bug?

**Comment by samithaf** [comment] 2016-05-02 10:49
@christopherthielen wonder this is related to https://github.com/angular-ui/ui-router/issues/2723

**Comment by christopherthielen** [comment] 2016-05-07 21:52
@Ben305 Here is a working plunker: http://plnkr.co/edit/0ww2TBT2WNPkZauuvEjT?p=preview

Can you provide additional information? The URL should be updating.

@dracula92107 I think you have a different problem, but you haven't provided enough information to give an answer.  

Can you open a new issue, and provide a plunker that reproduces the error?  Start here: http://bit.ly/UIR-Plunk

**Comment by christopherthielen** [comment] 2016-05-12 21:43
moving to alpha.6 milestone while waiting for info from @Ben305

**Comment by christopherthielen** [comment] 2016-06-26 03:10
Closing due to no activity

**Closed by christopherthielen** 2016-06-26 03:10 UTC
Labels: 1.0, bug
