### ISSUE TITLE
Parent state always waits for child state to resolve

### ISSUE THREAD

**Issue by shavo007** [angular-ui/ui-router#1761] opened 2015-02-19 00:06 UTC
Version 0.2.13
In my parent state I have a resolve. Currently, I do not inject the resolve key in any child state.

I assumed that my child state would not wait for this resolve/promise to be resolved. But when I set a timeout, I can see my child state does wait.

It states in the documentation  **"The resolve keys MUST be injected into the child states if you want to wait for the promises to be resolved before instantiating the children."** I have not injected in the userDetails yet to the billingController but it still waits

Code snippet:
```
    .config(function ($stateProvider, $urlRouterProvider, STATES) {
    $stateProvider
        .state(STATES.ROOT, {
            abstract: true,
            template:'<div ui-view=""></div>',
            resolve: {                  
                UserService: 'UserService',
               userDetails: function(UserService){
                   return UserService.getUserProfile();
                }

            }
        })
        .state(STATES.BILLING, {
            url: '/bill/checkClientContext.html',
           templateUrl: 'bill/checkClientContext.html',
            controller: 'BillingController'
        })
```

UserService.js
```
'use strict';
angular.module('nabc.data')
    .service('UserService', ['AjaxService', '$timeout','$q', function(AjaxService, $timeout, $q) {
        var getUserProfile = function() {
            var promise = AjaxService.get('userProfile');

            var deferred = $q.defer();
            $timeout(function(response){
                deferred.resolve(response);
            }, 5000);
            return deferred.promise;


        };

        return {
            getUserProfile: getUserProfile
        };
    }]);

```

Am I missing something?

Thanks,
Shane.

**Comment by eddiemonge** [comment] 2015-02-21 01:00
> The resolve keys MUST be injected into the child states if you want to wait for the promises to be resolved before instantiating the children

That means that if you want to use the promise in the child state, you have to inject it into it. All resolves on one state will be resolved before moving on to the next state, even if they aren't injected into that child:

> If any of these dependencies are promises, they will be resolved and converted to a value before the controller is instantiated and the $stateChangeSuccess event is fired.

States wait for the $stateChangeSuccess before moving on to the next.

**Comment by shavo007** [comment] 2015-02-23 00:38
Thanks for the reply mate. 

The statement above seems ambiguous tho, as I have not injected the resolve key into the child. 

Is there anyway for a parent resolve not to stall a child state unless it is injected?

Regards,
Shane.

**Comment by eddiemonge** [comment] 2015-02-23 19:03
Not really because it could be used in a controller. If you dont want it to resolve, then maybe it shouldnt be a resolve?

**Comment by goliney** [comment] 2015-03-26 14:11
I guess, documentation should be edited in order to clarify the moment with injection parent resolver into child state. It had been confusing me for hours before I met this issue.

**Comment by MFD3000** [comment] 2015-05-29 21:34
if the promise isnt required in any child, you could put it in the OnEnter event or similar.  The parent's controller is another option.

**Comment by christopherthielen** [comment] 2015-05-30 02:23
Wiki is wrong, sorry (feel free to update it). All resolves for all the states being entered are triggered and resolvesd before the transition will enter any states (regardless of the resolve being injected somewhere)




1.x will have resolve policy choices of "eager", "lazy" and "just-in-time"

**Comment by cannahum** [comment] 2015-08-20 18:18
I'm having a similar issue and in my case the parent state's resolve is authentication. You can appreciate that if a child state also has a resolve PostService.getPosts() from the back-end, I wouldn't want this resolve to do its job until the parent state has confirmed that there is an authenticated user. 

Any ideas how to solve this problem so that the the front-end is not requesting (and getting) posts without the parent state resolving authentication?

**Comment by christopherthielen** [comment] 2015-08-21 11:23
Inject the auth resolve into the child getPosts resolve

**Comment by cannahum** [comment] 2015-08-21 13:32
Thanks that worked! I send the resolve auth down to the posts resolve, I check:
resolve: {
  posts : function(auth, PostService)
    if (auth) {
      return getPosts();
    } else {
      $state.go('login')}}}

**Comment by nateabele** [comment] 2015-12-22 21:53
1.0 supports resolve policies, which address this. Thanks.

**Closed by nateabele** 2015-12-22 21:53 UTC
