### ISSUE TITLE
Child $stateParams empty object in state.resolve 1.0

### ISSUE THREAD

**Issue by xeii** [angular-ui/ui-router#2744] opened 2016-05-13 11:27 UTC
Version: 1.0.0-alpha.4

 * [Plunker](http://plnkr.co/edit/tnQZWcKCfn7iVZANrOHC?p=preview)
 * Related post on [StackOverflow](http://stackoverflow.com/questions/37139711/child-stateparams-empty-object-in-state-resolve)

The plunker example demonstrates similar state tree as I currently have in my application. The problem is when transitioning from home.list to home.foo.bar({ id: 1 }). The abstract state home.foo resolve shows correctly $stateParams = { id: 1} but the child state home.foo.bar shows only empty object.

Furthermore, $state.params is also empty object BUT shows correctly after the resolve block is completed. The value is bind to the view in the Plunker example.

**Comment by christopherthielen** [comment] 2016-05-13 17:42
I suggest using `$transition$.params()`.  We may be deprecating `$stateParams` because of how confusing it is.

- `$stateParams` is a global angular1 service which has the current committed state parameters
- However, when injected into a controller or resolve, `$stateParams` is a different object.
  - Has state parameters for the pending transition
  - Limited to only those parameters defined on the state being injected
- `$state.params` and the global `$stateParams` service ares updated *after* the transition completes.  During the transition (when resolves are being fetched, etc), these values still reflect the previous transition's parameters.

**Comment by christopherthielen** [comment] 2016-05-13 17:50
This is indeed a regression from 0.2.18, but I'm confused about 0.2.18's behavior. I don't think `$stateParams`  in `home.foo.bar` should have the `:id` parameter from `home.foo`.  Will look into it.

I think we will want to change the transition's `$stateParams` injectable to be the current value of `$transition$.params()`.  Then, all states will get all the params for the transition.

**Comment by christopherthielen** [comment] 2016-08-31 07:04
Closed by 8b961fcda8c47d70066bdb049a3d2fa08675dd27

`$stateParams` as injected into a controller is now an alias for `Transition.params()`, so it will receive all of the current transition's parameter values.

**Closed by christopherthielen** 2016-08-31 07:04 UTC
Labels: 1.0, bug
