### ISSUE TITLE
large ng-repeat lists transition slowly to update view

### ISSUE THREAD

**Issue by mbokil** [angular-ui/ui-router#3299] opened 2017-01-26 23:19 UTC
I grabbed the latest ui-router and angular 1.x from bower. I created a select list in angular using ng-repeat which is about 3K rows long. When switching route state there is a delay of 7 seconds on Chrome with a Macbook. Only fix I found was to delete the list child nodes by setting the parent container for the list to an empty string using innerHTML before switching state. This reduced the transition to about 1 sec. 

```
        var clinicList = document.getElementById('clinicList');
        if (clinicList) document.getElementById('clinicList').innerHTML = '';
        $state.go('selectshiftlistview');
```

**Comment by Vohidjon** [comment] 2017-02-20 11:12
I am having exactly the same issue. the transition from the 'heavy' state takes normal time on desktop browsers. but on iPad browsers (both safari and chrome) it takes about 15 seconds to transition from the state.
ui-router: v0.3.2
angular: v1.5.8

**Comment by christopherthielen** [comment] 2017-03-17 21:09
If this is ui-router's fault, I'd love to fix it.  However, I need a minimal reproduction to determine if it's the router being slow, or just angular itself.  

Please reproduce the behavior in a plunker:
- http://bit.ly/UIR-Plunk (for legacy 0.x versions)
- http://bit.ly/UIR-Plunk1 (for 1.0+ versions)

I'm closing this because there isn't enough information to act on.  Once a plunker is created, we can reopen and see if ui-router is at fault.

Note that there are some perf enhancements coming in rc.2 especially related to ui-sref and generating URLs.  See https://github.com/angular-ui/ui-router/issues/3361

**Closed by christopherthielen** 2017-03-17 21:09 UTC
Labels: not enough information, PlunkrPlease
