### ISSUE TITLE
Scope $destroy issue in 0.2.18

### ISSUE THREAD

**Issue by pitAlex** [angular-ui/ui-router#2614] opened 2016-03-10 16:49 UTC
Prior to this version when leaving a state, $scope $destroy was called first then the $scope of the new state was made then $stateChangeSuccess was called. Now I see order change completely: first the new state's $scope is made then  $stateChangeSuccess is called then $scope $destroy is called on the previous state. Is this part of the new changes? Because its messing up the way I handle some elements design between states.

**Comment by christopherthielen** [comment] 2016-03-14 18:12
Fixed in 84fd41268cb052c8af6b68bcf90324e7a1243146

I recommend using ver 0.2.15 until 0.2.19 is released, if the behavior in 0.2.18 is a problem for you.

**Closed by christopherthielen** 2016-03-14 18:12 UTC
Labels: bug

**Comment by dmitry-dedukhin** [comment] 2016-03-25 10:45
Could 0.2.19 be released sooner than usually?
This bug breaks many cases.
For example, if somebody doing some cleanup in services on scope destroy, then at the moment the new data (which was set in service on new scope init) could be cleaned up!

**Comment by christopherthielen** [comment] 2016-03-25 22:04
@dmitry-dedukhin I recommend using 0.2.15 (the release prior to the one where this bug was introduced) until 0.2.19 is released.

**Comment by dmitry-dedukhin** [comment] 2016-03-26 08:53
@christopherthielen I've updated from 0.2.15 a month ago.
And as far as I remember this update was caused by two $stateChangeStart events bug in 0.2.15. This was critical for me so reverting is not an option...

**Comment by phazei** [comment] 2016-05-11 02:19
Is there even going to be a 0.2.19?  It's a pretty bad state to leave the 0.2.x branch in... :(

**Comment by christopherthielen** [comment] 2016-05-11 02:24
There will be a 0.2.19. I can only do so much in my spare time, sorry.
