### ISSUE TITLE
$stateChangeSuccess on $rootScope is fired before $destroy is called on previous scope.

### ISSUE THREAD

**Issue by SHarpritSingh** [angular-ui/ui-router#3059] opened 2016-10-04 08:49 UTC
This is somewhat similar to issue angular-ui/ui-router#2485 but the difference being `$stateChangeSuccess` is registered on `$rootScope` rather than the `$scope` of the controller. 

In this case, state change success event on root scope is fired before $destroy is triggered on the previous scope.

Is this event order expected/desired or should this order even matter?

https://jsfiddle.net/SHarprit/zLnayf00/

**Comment by christopherthielen** [comment] 2016-10-04 17:14
This is expected behavior.  Read this comment in the linked issue: https://github.com/angular-ui/ui-router/issues/2485#issuecomment-184234578

You can see it easily in the source code: https://github.com/angular-ui/ui-router/blob/legacy/src/viewDirective.js#L206-L208

In legacy codebase, views are updated in response to a `$stateChangeSuccess`

Closing because I've answered the question

**Closed by christopherthielen** 2016-10-04 17:14 UTC
