### ISSUE TITLE
Wrong url when navigating backwards

### ISSUE THREAD

**Issue by KarolinaM339** [angular-ui/ui-router#2757] opened 2016-05-18 18:44 UTC
When navigating backwards state changes but url stays the same.

For example if I were going from state1 to state2 the url's respectively would change from /state1 to /state2. But when I decide to go back from state2 to state1 url stays /state2.

I checked states url changes correctly, but when I looked at $locations newState and oldState at locationChangeSuccess event I saw something unusual. 
When I press to go back at first everything seems fine oldState is /state2, newState - /state1,
but then for some reason event is trigered again and now oldState is /state1 and newState is /state2.

What can cause this kind of problem?

**Comment by christopherthielen** [comment] 2016-05-19 00:55
I'm not sure.  Can you reproduce it in a plunker? http://bit.ly/UIR-Plunk

**Comment by KarolinaM339** [comment] 2016-05-19 18:52
I'm not able to restore this behavior in plunker.

**Comment by eddiemonge** [comment] 2016-06-02 19:17
I really want to close this as a cant reproduce.

**Closed** 2016-06-07 20:07 UTC
Labels: PlunkrPlease
