### ISSUE TITLE
Calling `otherwise` after state match 

### ISSUE THREAD

**Issue by vivex** [angular-ui/ui-router#3358] opened 2017-03-03 06:55 UTC
This is a:

- [ ] Bug Report
- [ ] Feature Request
- [x] General Query 

My version of UI-Router is: v0.2.18

Angular Version: 1.3.15

# General Query

Please direct general implementation questions to StackOverflow: 
http://stackoverflow.com/questions/ask?tags=angularjs,angular-ui-router

Please review the Sample Application which highlights common approaches:
https://github.com/ui-router/sample-app-ng1

- [ ] I have already asked my question on StackOverflow and nobody could answer the question

- [ ] I have already reviewed the sample application for examples of common approaches

- [x] I believe my question can only be answered by the UI-Router maintainers

State url is : `{providerSlug:([^subs])}/:orgName/:projectName/runs/{runNumber:[0-9]{1,8}}`

URL which i am hitting in browser: `/github/vivex/sample-1/runs/12`

It matches the ui-router state , and loads the controller, and just after that calls otherwise and redirects to default page,

It is not triggering `$stateNotFound ` neither `$stateChangeError `,  $location object in otherwise callback says that `$$state` is null.

If i define state without regular expression then it works fine.
Can someone please tell me whats wrong here?

**Comment by christopherthielen** [comment] 2017-03-25 16:19
Please provide a plunker which reproduces the problem:  http://bit.ly/UIR-Plunk
Closing because there is no plunker.  When there is a plunker, re-open the issue and we can try to diagnose.

--

There are two potential problems with your `providerSlug` regexp:

- It only matches a single character.  It does not match `github` because `[^subs]` matches a single character that is not `s`, `u`, or `b`.

- I think it must be a non-capturing regexp.  Eliminate the parentheses

**Closed by christopherthielen** 2017-03-25 16:19 UTC
Labels: PlunkrPlease
