### ISSUE TITLE
Resolve called twice when state url needs to be encoded

### ISSUE THREAD

**Issue by bandrzejczak** [angular-ui/ui-router#2408] opened 2015-12-03 09:00 UTC
I've seen issue #37 which was resolved, but the problem still occurs if the state url needs to be encoded. Here's how it works:
If we have a state like this:

```javascript
.state('state', {
        url: '/state/?path',
        templateUrl: 'template.html',
        resolve: {
          test: function ($stateParams) {
            console.log("Resolve called. Path = " + $stateParams.path);
          }
        }
      })
```

and have two links:

```html
<a ui-sref="state({ path: 'testPath' })" translate>Test 1</a>
<a ui-sref="state({ path: '/testPath/' })" translate>Test 2</a>
```

Then for the first link resolve will be called once with path equal `testPath`, but for the second link resolve function will be called once for `/testPath/` path and once for `%2FtestPath%2F`.

**Comment by eddiemonge** [comment] 2015-12-03 19:58
Im going to call this a duplicate of the #1973 (might not be the right one). Once the double encoding problem is fixed then if this isn't it can be reopened

**Closed by eddiemonge** 2015-12-03 19:58 UTC
Labels: duplicate

**Comment by Bessonov** [comment] 2016-10-01 16:47
@eddiemonge 

I still experience this issue with ui-router#0.2.18 if I use slug in urls:

```
.config(['$stateProvider', '$urlRouterProvider', '$urlMatcherFactoryProvider',
        function($stateProvider, $urlRouterProvider, $urlMatcherFactoryProvider) {
                $urlRouterProvider.otherwise('/');
                $urlMatcherFactoryProvider.type('slug', {
                        encode: function(str) { return str && str.replace(/ /g, '-'); },
                        decode: function(str) { return str && str.replace(/-/g, ''); },
                        is: angular.isString,
                        pattern: /[^/]+/
                });
        }
])
```

Is here any workaround?
