### ISSUE TITLE
How to ignore history removal in popstate

### ISSUE THREAD

**Issue by redhead** [angular-ui/ui-router#2545] opened 2016-02-10 16:32 UTC
In our project, we have this case: A user is on a page with a form, that they fill in and then they hit back button, which means it triggers a new state transition. However we have a dirty check handler that prevents going to another state if the form is dirty. When the confirm dialog is opened, the history item was already removed (using popState I guess) and moved to "forward" button. How can I prevent this if the user chooses to stay on the page?

I found that popState doesn't support preventDefault. So I thought adding the url back using pushState, but that would destroy the "forward" button history (if there was some).

Have you guys ever ran into similar scenario?

**Comment by IainCole** [comment] 2016-02-10 16:49
We had a similar issue, we had to get a little creative.

Basically when you enter the state you can manually push another history entry into the stack. You can then listen to popState as normal and at that point you are still on the same state but the history has changed. You then have to handle either re-adding the phantom history state or calling .back() again to actually go back. 

This only really covers the back button and doesn't really handle someone clicking on a history entry more than 1 item up the stack.

The other thing to remember is that you have to remove that phantom history entry on any valid state transition out of that state.

**Comment by eddiemonge** [comment] 2016-03-03 21:43
How are you doing the check? I think that might be where your problem is. Can you make a plnkr example please?

**Comment by redhead** [comment] 2016-03-04 10:38
The whole dirty check thing is done by the dirtyCheckHandler service (at the bottom of index.html). Use the following link to try it out and  see the URLs and history state changing in the browser:

http://run.plnkr.co/tloh05zZO21jr4UB/

**Comment by eddiemonge** [comment] 2016-03-04 19:30
says its expired

**Comment by redhead** [comment] 2016-03-04 21:30
Here, I created it again: http://plnkr.co/edit/IHOMJD9cHvd966kGKAXW?p=preview, open it in separate window

**Comment by eddiemonge** [comment] 2016-03-14 20:06
Yeah I think you need something like http://stackoverflow.com/questions/821011/how-do-you-prevent-a-webpage-from-navigating-away-in-javascript

Basically you need to prevent the page from navigating away using pure window methods instead of watching state change events

**Comment by eddiemonge** [comment] 2016-03-14 20:07
Closing as this is more of an implementation issue and not a bug. The discussion can keep going but check around on stackoverflow as something like this has probably been answered on there already

**Closed by eddiemonge** 2016-03-14 20:07 UTC

**Comment by redhead** [comment] 2016-03-14 22:39
But it is not navigating away, unbeforeunload does not do the trick as it is pure javascript navigation insde a single-page application and not unloading and loading a new page.
