### ISSUE TITLE
Ng1StateDeclaration.onEnter documentation incorrect

### ISSUE THREAD

**Issue by smhc** [angular-ui/ui-router#3153] opened 2016-11-15 02:16 UTC
The documentation for:
https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#onenter

States the interface as:
onEnter: function(trans, state) {

But it is actually:
onEnter: function(injectable providers) {

Using the interface from the documentation generates the error:

Error: [$injector:unpr] Unknown provider: transProvider <- trans

**Comment by christopherthielen** [comment] 2016-11-16 21:35
Thanks for the report. 
This is a duplicate of #3072 and is fixed by #3076

The docs site will be updated when the next version is released

**Closed by christopherthielen** 2016-11-16 21:35 UTC
