### ISSUE TITLE
Transitioning to state without notifying stops transition to happen

### ISSUE THREAD

**Issue by alejandroiglesias** [angular-ui/ui-router#1727] opened 2015-02-03 19:36 UTC
Hi, in order to make a special transition that should not be intercepted by listening to `$stateChangeStart` event, i'm calling `$state.go` with `{notify: false}` options object.

```
$state.go('proposal.level', null, {notify: false});
```

The problem is that the state is never transitioned to, only URL is updated. My version of uiRouter is 0.2.7. Can't update, sorry, since something stops working in the app around 0.2.10 (will try to check that in the near future, but not in the current timeframe available).
I would appreciate any suggestions in how to achieve my desired result.
Thanks in advance!

**Comment by nateabele** [comment] 2015-03-27 17:34
Please post a plunkr that demonstrates the issue, thanks.

**Comment by thewilli** [comment] 2015-08-02 12:39
I had the same issue with UI Router 0.2.15.

I created a [Gist](https://gist.github.com/thewilli/f2fc71ce982f46e1dd3e) with a MWE, as it is easier to play around with URL-based states.

The example checks whether a user is logged in (statically *false* in the MWE) and the redirects to a login page. When setting *notify* to *false*, only the URL is updated, but the template content is not set - the *ui-view* element is not filled at all.

**Comment by thewilli** [comment] 2015-08-02 12:44
@nateabele  as there is an example now, would you please consider removing the label you've assigned?

**Comment by eddiemonge** [comment] 2015-08-18 20:50
http://plnkr.co/edit/h3T8LK5o15zpRuIzrgFk?p=preview

notify false prevents the stateChange events from firing, which effectively prevents the state change from happening. I'm not really sure if thats the expected behavior. @nateabele ?

**Comment by eddiemonge** [comment] 2015-08-18 20:51
Nevermind. closing as a duplicate of https://github.com/angular-ui/ui-router/issues/1158

**Closed by eddiemonge** 2015-08-18 20:51 UTC
Labels: duplicate
