### ISSUE TITLE
$transitions.onError() and $state.defaultErrorHandler() are not executed when resolved is rejected

### ISSUE THREAD

**Issue by mikeborozdin** [angular-ui/ui-router#3212] opened 2016-12-19 13:11 UTC
Hi,

I'm using version 1.0.0-beta.3. And $transitions.onError()` and `$state.defaultErrorHandler()` are not invoked when a promise inside resolve is rejected. 

More specifically, in my resolve clause I call an Angular service which has a promise that gets rejected:

```
resolve: {
  data: ['dataService', function (dataService) {
    return dataService.getData();
  }]
}
```

and the service:

```
function getData () {
  var deferred = $q.defer();

  deferred.reject();

  return deferred.promise;
}
```

On the other hand, if `getData()` throws an exception, then both errors handler will get fired.

**Comment by christopherthielen** [comment] 2016-12-19 16:32
Can you reproduce it in a plunker?

It seems to work for me: http://plnkr.co/edit/MBWQk1x8umyjBK2tRHxU?p=preview

**Comment by mateid** [comment] 2017-01-10 23:34
I am experiencing a similar issue on rc1. I use transition hooks to hide a navigation bar and use the `onStart` hook and `onError` hooks. When the transition is to a different state than current state everything works well. When transitioning to the exact state neither hook is invoked and neither is the default error handler. The documentation states the `onError` hook should be invoked for transitioning to the same state. I can open a new issue if needed but it seems closely related to what @mikeborozdin is experiencing.

I have a plunk here http://run.plnkr.co/Wu0BhotjY38F5q4a/

**Comment by christopherthielen** [comment] 2017-01-11 19:52
@mateid can you link to the original plunker?  `run.plnkr.co` times out after a few minutes, so your URL is 404

**Comment by mateid** [comment] 2017-01-11 20:05
Sorry, my bad. Here goes: http://plnkr.co/edit/UoJVqr1KoMXjRhQmV2yT?p=info

**Comment by christopherthielen** [comment] 2017-01-11 21:14
@mateid 

> The documentation states the onError hook should be invoked for transitioning to the same state.

Can you point this out? I think we used to call `onError` for ignored transitions (During the 1.0 alphas), but should not do that any more.  Now, an [ignored transition is not even run](https://github.com/ui-router/core/blob/707821609bdf24a01f358225380ff56e1564daf0/src/transition/transition.ts#L653-L657).  If the docs still say that, they need to be updated.

Ignored transitions can still be handled using `onBefore` though (see updated plunker: http://plnkr.co/edit/0BSqsj0F69IcTHEtCNQ0?p=preview)

**Comment by christopherthielen** [comment] 2017-01-11 21:20
@mikeborozdin here's a plunker demonstrating that the default error handler is invoked, and so is `onError` when a resolve fails due to a resolve rejection:  http://plnkr.co/edit/aI9DlyugPtW1dUjSExe2?p=preview

Closing for now.  Reopen when you can reproduce the error (in a plunker, please)

**Closed by christopherthielen** 2017-01-11 21:20 UTC
Labels: PlunkrPlease

**Comment by mateid** [comment] 2017-01-12 00:10
@christopherthielen fabulous, thank you!
See here for the docs (fifth item in the bullet list): https://ui-router.github.io/ng1/docs/1.0.0-rc.1/classes/transition.transitionservice.html#onerror

**Comment by christopherthielen** [comment] 2017-01-12 00:11
@mateid thanks, I'll make sure to remove that from the docs!
