### ISSUE TITLE
function cleanupLastView needs to have currentScope destroyed instead of willbeDestroyed?

### ISSUE THREAD

**Issue by xtianus79** [angular-ui/ui-router#2510] opened 2016-02-01 22:27 UTC
After finding this bug refrenced here... https://github.com/angular-ui/ui-router/issues/2505  I have figured out where the bug affecting our application is coming from. 

The function cleanupLastView has a currentScope that will be destroyed... However it doesn't seem to actually destroy and thus our application runs the modal pop up once (refresh the browser without a full browser reload) and then it won't do it again upon a state change.  By adding the currentScope.$destroy(); to the current scope fixes the issue.  I am assuming the updated function is trying to update the current scope if it needs to be destroyed whether it is old or new?  

    function cleanupLastView() {
          var _previousEl = previousEl;
          var _currentScope = currentScope;

          if (_currentScope) {
            _currentScope._willBeDestroyed = true;
            **currentScope.$destroy();**
          }

          function cleanOld() {
            if (_previousEl) {
              _previousEl.remove();
            }

            if (_currentScope) {
              _currentScope.$destroy();
            }
          }

          if (currentEl) {
            renderer.leave(currentEl, function() {
              cleanOld();
              previousEl = null;
            });

            previousEl = currentEl;
          } else {
            cleanOld();
            previousEl = null;
          }

          currentEl = null;
          currentScope = null;
        }

        function updateView(firstTime) {
          var newScope,
              name            = getUiViewName(scope, attrs, $element, $interpolate),
              previousLocals  = name && $state.$current && $state.$current.locals[name];

          if (!firstTime && previousLocals === latestLocals || scope._willBeDestroyed) return; // nothing to do
          newScope = scope.$new();
          latestLocals = $state.$current.locals[name];

perhaps it is related to the angular version from this fix? 
https://github.com/angular-ui/ui-router/commit/9b6d9a2d0ce4ae08384165cb517bddea59b67892

**Comment by nateabele** [comment] 2016-02-02 01:49
Okay, sounds like a duplicate of #2485 then.

**Closed by nateabele** 2016-02-02 01:49 UTC
