### ISSUE TITLE
Not able to change templateUrl based on dynamic param (1.0.0-alpha5)

### ISSUE THREAD

**Issue by motin** [angular-ui/ui-router#2831] opened 2016-06-22 23:16 UTC
Here is a plunker demonstrating the issue: http://plnkr.co/edit/b3pOQKRmuJRS7RyLbDP8
Also a plunker with "dynamic: false" which shows the expected behavior: http://plnkr.co/edit/rTCYeIwDnWcBPSGWFAon?p=preview

Steps to reproduce:
1. Go to state "home.foo"
2. Notice how the alert, called from the templateUrl function, informs about the template change
3. Click the link to switch to the 3x3 layout

Expected to happen:
An alert, called from the templateUrl function, should inform about the template change, then the template used for the ui-view should be updated to the return value of the function.

What actually happens:
The templateUrl function is not called and the correct template is not switched to. Only the uiOnParamsChanged callback is triggered.

Possible workarounds:
- Use ng-include and scope variables to determine the templates used instead of nested views and states. This would work but the whole point of ui-router is to get rid of such horrible hacks
- Is it maybe possible to change the templateUrl from within uiOnParamsChanged callback? Maybe by first rewriting the app to use components instead of templateUrl+controller? Or by modifying the state's internals using $state.get() or $state.get().$$state() ?

**Comment by christopherthielen** [comment] 2016-06-23 20:17
Thanks for the excellent issue report.

1. Views are processed when a state is entered.  This includes processing `controllerProvider` or `templateProvider`.
2. Changes to dynamic parameters do not cause a state to be re-entered. 

Because of this, the behavior you reported with is what I expect should happen.

Are you avoiding exiting/re-entering the state (`dynamic: false`) because you don't want to re-fetch resolves?

**Comment by christopherthielen** [comment] 2016-06-23 21:07
By using the `$view` service directly, you can reload the views pretty easily:
http://plnkr.co/edit/1OGFV8HxrXoqFpNX8kPZ?p=preview

```js
function reloadViews($transition$, stateName) {
    // Get a reference to the built state object
    let state = $state.get(stateName).$$state();
    
    // The currently active ViewConfig(s) for the given state
    // Note: viewConfigs isn't *currently* public, but I'm planning to create an accessor
    let oldConfigs = $view.viewConfigs.filter(view => view.node.state === state);
    // Find the node for the state in the "to path" (which has the updated parameters)
    let node = $transition$.treeChanges().to.find(node => node.state === state);
    
    // Build new ViewConfigs for all the state's views using the node from the "to path"
    let newConfigs = Object.keys(state.views)
        .map(name => $view.createViewConfig(node, state.views[name]))
        // Flatten 2D array to a 1D array
        .reduce((acc, arr) => acc.concat(arr), []);
    
    // Load the ViewConfigs (this fetches templates, etc)
    $q.all(newConfigs.map(cfg =>  cfg.load())).then(() => {
      // Then deactivate the old configs and activate the new ones
      oldConfigs.forEach(cfg =>  $view.deactivateViewConfig(cfg));
      newConfigs.forEach(cfg => $view.activateViewConfig(cfg));
      // finally, tell the ui-views to update based on the newly activated configs
      $view.sync();
    })
  }
```

**Comment by christopherthielen** [comment] 2016-06-24 18:14
Closing because this works as designed, and I provided a workaround

**Closed by christopherthielen** 2016-06-24 18:14 UTC

**Comment by motin** [comment] 2016-06-27 22:01
@christopherthielen Thanks for the feedback and the workaround. This really helps understand what dynamic params are and are not, as well as provides a way to tinker and experiment with state internals until a good solution can be achieved. I just wished there was more documentation and examples of dynamic params, but I guess that is on the roadmap for 1.0 :)
