### ISSUE TITLE
resolve in view do not work . 

### ISSUE THREAD

**Issue by lili21** [angular-ui/ui-router#2717] opened 2016-04-27 09:44 UTC
It works fine in `0.2.11` version. But I want to use `reloadOnSearch` feature, So I upgrade to `0.2.18`, and   all resolve in view do not run. 

Does this feature be removed in specific version ? I don't see any about this be mentioned in [changelog](https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md)

Below is my state config.

![2016-04-27 5 48 15](https://cloud.githubusercontent.com/assets/4456380/14848280/85a335a4-0c9f-11e6-8c06-93d1a52a7610.png)

**Comment by christopherthielen** [comment] 2016-05-02 15:53
I think this is dupe of #2008

In short, we never documented that `resolve` could be applied to `views:`.  
I think we considered it a vestigial remnant and removed the code.

I recommend moving the resolves from the view to the state.

**Comment by christopherthielen** [comment] 2016-05-02 15:53
closing as dupe

**Closed by christopherthielen** 2016-05-02 15:53 UTC
