### ISSUE TITLE
Nested state controller requires ui-view

### ISSUE THREAD

**Issue by gbittmann** [angular-ui/ui-router#2775] opened 2016-05-27 15:16 UTC
For the controller of a child to be used, you must put a ui-view in the parent. It does not matter if you define a template in the child or not (as indicated in the doc), the only difference is if you have a ui-view element in the parent. 

There is no template content for the child so you just have an extra tag in the parent to make the child controller load.

```
state('example', {
    url: "/example",
    templateUrl: "html/example.html",
    controller: 'ExampleCtrl',
}).
state('example.child', {
    url: "/search/:search",
    controller: 'ExampleChildCtrl',
})
```

example.html (controller works):
```
<body>
    <div ui-view></div>
<body>
```

example.html (controller does not work):
```
<body>
<body>
```

**Comment by christopherthielen** [comment] 2016-05-27 15:49
Yes, you need a `ui-view` to load any children views into. 

Having a state with only a controller doesn't really align with the intended use of ui-router.  The view is generally thought of as a standalone component having a template, which is then loaded into some parent's ui-view.  A standalone controller is essentially sugar for a component with an empty template.  That component still needs to be loaded somewhere, so the ui-view is necessary.  If you want to simply run code when a state is entered, use `onEnter`.


The industry is converging on a component architecture.  A standalone controller doesn't make sense in that mindset.  In fact, in ui-router 1.0, we require that all views have a template. The workaround for your app is simple, as you've noted... you need a `<ui-view>` for the child component to load into.  

Since this is working as designed and there's a simple workaround, closing as wontfix.

**Closed by christopherthielen** 2016-05-27 15:49 UTC
Labels: wontfix
