### ISSUE TITLE
Route to component: Support '&' bindings to callback functions

### ISSUE THREAD

**Issue by marksq** [angular-ui/ui-router#3111] opened 2016-10-26 12:17 UTC
It looks like 1.0.0-beta3 is only working with '<' or '=' bindings with the state.component() syntax.

Do you plan to support '&' bindings like this:

``` javascript
.state('page', {
    url: '/page', 
    component: 'myPage', 
    resolve: {
        onUpdate: // Some method in Service, that call when user update a data 
    }
})
```

where the component is:

``` javascript
.component('child', {
    bindings: {
        onUpdate: '&'
    },
    ...
})
```

and in component's template

``` html
<form ng-submit="$ctrl.onUpdate(value)">...
```

?

**Comment by christopherthielen** [comment] 2016-10-26 16:16
the short answer is that you can use `'<'` binding for that

The long answer can be found here: https://github.com/angular-ui/ui-router/issues/3099#issuecomment-255242756

closing as duplicate of #3099 please add your thoughts to that ticket

**Comment by christopherthielen** [comment] 2017-01-03 05:52
Reopening because I agree that wiring a component's output (`&` binding) to a function returned by a resolve could be useful.  See 

I propose that given this component:

```js
.component('foo', {
  bindings: { onEvent: "&" },
  template: "<a ng-click="$ctrl.onEvent({ data: 123 })>save 123</a>"
});
```

these examples should work:

# example 1 
(only works when unminified)
```js
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: (ServiceAPI) => (data) => ServiceAPI.saveData(data)
  },
});
```


# example 2

```js
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: (ServiceAPI) => [ 'data', (data) => ServiceAPI.saveData(data) ]
  },
});
```



# example 3

```js
resolveFn.$inject = ['ServiceApi'];
function resolveFn(ServiceApi) {
  saveData.$inject = ['data'];
  function saveData(data) {
    ServiceAPI.saveData(data);
  }
  return saveData;
}
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: resolveFn
  },
});
```

---

The resolve is still invoked as usual when the state is entered.  For this to work, the resolve must return a function.  The "&" binding in the component will pass through to the returned function. 

When the template is being created, the resolve function arguments are introspected. The function is faux injected using the locals passed by the component.

---

## Generated templates:

Example 1 and 2:
```
<foo on-event="$resolve.onEvent(data)"></foo>
```
Example 3 (finds the last element of the array, which should be the fn)
```
<foo on-event="$resolve.onEvent[1](data)"></foo>
```

**Comment by christopherthielen** [comment] 2017-01-03 05:56
Reopening, since I agree that wiring a component's output (`&` binding) to a function returned by a resolve could be useful.  

I propose that given this component:

```js
.component('foo', {
  bindings: { onEvent: "&" },
  template: "<a ng-click='$ctrl.onEvent({ data: 123 })'>save 123</a>"
});
```

these examples should work:

# example 1 
(only works when unminified)
```js
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: (ServiceAPI) => (data) => ServiceAPI.saveData(data)
  },
});
```


# example 2

```js
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: (ServiceAPI) => [ 'data', (data) => ServiceAPI.saveData(data) ]
  },
});
```



# example 3

```js
resolveFn.$inject = ['ServiceApi'];
function resolveFn(ServiceApi) {
  saveData.$inject = ['data'];
  function saveData(data) {
    ServiceAPI.saveData(data);
  }
  return saveData;
}
.state('foo', {
  component: 'foo',
  resolve: {
    onEvent: resolveFn
  },
});
```

---

The resolve is still invoked as usual when the state is entered.  For this to work, the resolve must return a function.  The "&" binding in the component will pass through to the returned function. 

When the template is being created, the resolve function arguments are introspected. The function is faux injected using the locals passed by the component.

---

## Generated templates:

Example 1 and 2:
```html
<foo on-event="$resolve.onEvent(data)"></foo>
```
Example 3 (finds the last element of the array, which should be the fn)
```html
<foo on-event="$resolve.onEvent[1](data)"></foo>
```

**Closed** 2017-01-03 06:29 UTC
Labels: 1.0, feature

**Comment by timothyswt** [comment] 2017-01-09 18:00
IMO the usage of returning a function that takes event arguments is strange.  
I would almost rather declare events separately from resolve and the usage be different rather than declaring a resolve and returning a function. It feels like we are overloading the intent of resolve.

If you think of it from the Ember perspective of the model resolver, the intent of model is to either return a promise or an object as the data model which is available on the related controller/component. Events are declared differently. 

I feel like we should be able to create events that "require" a service on the route definition rather than injecting a service to a function that returns a function. 
example:

```javascript
$stateProvider.state('foo', {
  require: ['service1', 'service2'], //<-- requirable services available on resolve and event 'this' context
  events: {
    // not injectable, but requireable
    // this event would be available to bindings.
    onEvent: (eventData) => this.service2.handleEvent(data)
  },
  resolve: {
    dataModel: (service3) => this.service1.get(service3.result) //<-- returns data or a promise like today
  }
});
```

**Comment by timothyswt** [comment] 2017-01-09 18:43
> That's a good argument, and I mostly agree. I'm hesitant to increase the API surface area further, however.

I understand the hesitation. I do think however, a wider API surface that is more concise is easier to understand than an overloaded API surface that is more complex.
