### ISSUE TITLE
Child view loaded twice when object id is a url (hateos api)

### ISSUE THREAD

**Issue by danielabar** [angular-ui/ui-router#2250] opened 2015-09-18 12:51 UTC
When using a hateos style rest api, the object id's are url's, that the client follows to get more details. In this case, when using `ui-sref` in the template, the child view is loaded twice, and the resolves also run twice. And the active state is lost.

[Plunker demonstrating the issue](http://plnkr.co/edit/VXlYZ5?p=preview)

I've documented a workaround in the plunker readme, in case anyone else is having this issue.

**Comment by nateabele** [comment] 2015-09-18 13:23
> When using a hateos style rest api

:^5: for good architectural style.

@christopherthielen This looks like a new incarnation of the old encoding/double-transition bug. The problem is the slashes in the URL parameters. I tested the plunkr against master and it's still an issue. The encoding/decoding isn't symmetrical, so `$urlRouter` is seeing the resulting URL as being different from the one that initiated the transition.

**Comment by christopherthielen** [comment] 2015-09-20 22:33
those pesky slash encodings...  I had thought I had the encoding/decoding working symmetrically at one point.  

@nateabele got any thoughts on a better way to manage this without the browser's built in decoding getting in the way?  A custom serialization that avoids url encoding in certain cases, or something?

@danielabar note: you can fool around with making a custom Type to make your use case work.  Change your url from "/:id" to use the built-in any type, for example: "/{id:any}" and the url does not get encoded at all, and your plunkr behaves better.

**Comment by nateabele** [comment] 2015-09-21 15:52
@christopherthielen I merged my PR for raw types to 1.0. I'll set up a test against that later today.

**Comment by christopherthielen** [comment] 2015-09-22 00:10
I'd like this to work with string Type. Any string (including those with
slashes) should have symmetrical encoding

**Comment by christopherthielen** [comment] 2016-01-23 06:14
http://plnkr.co/edit/SH4rrZ?p=preview

**Closed** 2016-01-23 06:29 UTC
